### ISSUE TITLE
Criar ação de menu para acrescentar dispositivo do mesmo tipo antes e depois do dispositivo atual

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#106]
Adicionar, no menu de contexto, as opções de:

- Acrescentar &lt;tipo do dispositivo atual&gt; antes deste dispositivo.
- Acrescentar &lt;tipo do dispositivo atual&gt; após este dispositivo.

A ação deve acrescentar dispositivo do mesmo tipo antes ou depois do dispositivo selecionado e posicionar o cursor no novo dispositivo para edição.

O novo dispositivo deve ser criado de acordo com as regras do modo de edição correspondente (emenda ou edição).

**Comment by jholanda** [comment]
E os demais dispositivos? por exemplo, a ação de incluir um parágrafo também fará parte do menu de um artigo, p ex.?

**Comment by fragomeni** [comment]
Por enquanto não. Vamos deixar no esquema do enter e transformação.
