### ISSUE TITLE
Criar solução de layout para alertas globais.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#108]
A ideia é apresentar alertas informativos que permanecem exibidos até que o usuário o descarte.

Criar opções de severidade: Sucesso, Erro, Alerta e Informação.

Exemplo:

"Cada emenda somente pode referir-se a apenas um dispositivo, salvo se houver correlação entre dispositivos. Verifique se há correlação entre os dispositivos emendados antes de submetê-la."

**Comment by arthurcordeiro** [comment]
Refina estilo dos alertas globais success, info, warning e danger. Remove hífen do início das mensagens.

<img width="756" alt="Captura de Tela 2022-05-11 às 09 33 04" src="https://user-images.githubusercontent.com/1903603/167850754-7ca013ad-6057-434a-bdb6-e64567fef36d.png">

https://github.com/lexml/lexml-eta/commit/c8382b6c5503dc8bc8b89667ad5967ef766b4bdd

**Comment by fragomeni** [comment]
Ainda é necessário que o alerta possa ser fechado (com um x provavelmente) pelo usuário. A implementação no sistema é objeto de outro tíquete (#109)

**Comment by arthurcordeiro** [comment]
Oi, @fragomeni . No experimento que fiz aqui não ficaram bons os alertas acima das abas pois dependendo do número de avisos perderíamos altura espremendo o editor de emendas. 

Criei uma aba "Avisos" com um badge PULSANTE com o número de alertas. Está chamando bem a atenção do usuário sem deficiência.

Seria bacana pensarmos um alerta sonoro pra cada tipo: Sucesso, Erro, Alerta e Informação para que a pessoa com deficiência fosse alertada também.

<img width="854" alt="Captura de Tela 2022-05-12 às 08 17 10" src="https://user-images.githubusercontent.com/1903603/168062814-772d2cbe-f29c-40be-952d-a6a37e44da4f.png">

https://github.com/lexml/lexml-eta/commit/16cda8c6ce159371dda2fff57309d60e4e9655c1
