### ISSUE TITLE
Criar componente de interface gráfica para alertas globais.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#109]
Estes alertas devem permanecer visíveis até que o usuário o descarte ou sejam removidos programaticamente.

Além de apresentar alertas, deve ser possível verificar a existência de um alerta ou remover um alerta.

Este componente seria de uso comum a todos os demais dentro do componente de edição de emenda.

----
Modelo do alerta
```
{
  tipo: "Erro", "Alerta", "Sucesso", "Info"
  mensagem: string;
  podeFechar = true;
  id: string;
}
```

----
Criar lista de alertas no ui do estado.
Criar ações redux para:
- Adicionar alerta.
- Remover alerta com base no id.
- Remover todos os alertas.

----
Começa a pulsar quando entrar nova mensagem.
Ao visualizar os alertas (selecionar a aba de alertas) para de pulsar.

**Comment by erivanio** [comment]
- remover contador da badge de notificação de alertas se for 0
- ao criar novo alerta, a notificação da aba deve pulsar
- ao clicar na aba "avisos", o badge de notificação deve parar de pulsar
