### ISSUE TITLE
“Art. 1-A” deve ter ponto após a letra

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#115]
O label de artigo deve sempre terminar com ponto quando tiver sufixo de encaixe, independentemente de uso do ordinal para artigos até o 9º.

**Comment by erivanio** [comment]
![Captura de Tela 2022-05-13 às 14 24 10](https://user-images.githubusercontent.com/5238433/168336059-4017ac16-661d-47dd-bb6e-4da247486c19.png)
Fique com uma dúvida em relação ao comando de emenda, no texto deve-se adicionar o ponto final?

**Comment by jholanda** [comment]
Não, apenas após o rótulo

**Comment by fragomeni** [comment]
@erivanio, não tinha explicado bem as regras. No comando de emenda nunca tem o ponto. No rótulo, do artigo 1º ao 9º utiliza-se o ordinal sem ponto, do 10 em diante e em todos que terminarem com -<letra> utiliza-se o ponto no final. A regra é a mesma para parágrafo e não estava implementada. Já fiz a correção no código.
