### ISSUE TITLE
Adicionar botão de remover formatação no editor de articulação

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#119]
Semelhante ao da justificativa.

![image](https://user-images.githubusercontent.com/5323676/167727762-bc08bce7-d7e6-486f-ad33-f0d19c17e7af.png)

**Comment by erivanio** [comment]
@fragomeni , as funções de bold e italic do editor, chamam a função [this.formatacaoAlterada();](https://github.com/lexml/lexml-eta/blob/87f4051e6defe1e1a443163050ff03684923c11c/src/components/editor/editor.component.ts#L185). O remover formatação deve chamar alguma outra função ou posso somente usar a padrão do quilljs?

**Comment by fragomeni** [comment]
@erivanio, pode usar o padrão do editor.
