### ISSUE TITLE
Não permitir incluir novo dispositivo do mesmo tipo quando o pai está suprimido

### ISSUE THREAD

**Issue by robsonbarrosdf** [lexml/lexml-eta#125]
O editor não deve permitir que um novo dispositivo do mesmo tipo seja adicionado quando seu pai estiver suprimido.
Por exemplo, não deve ser possível adicionar mais um inciso de parágrafo quando o parágrafo pai estiver suprimido.

![image](https://user-images.githubusercontent.com/37158063/168688576-55c050a4-fff1-4b0a-b89a-2131c7294ad1.png)

**Comment by jholanda** [comment]
Agora é feito um teste no adicionar dispositivo, embora o ideal é que seja feito um refatoramento para que não seja executada uma ação de teclado que não conste das ações permitidas.
