### ISSUE TITLE
Tornar responsíveis as alturas das abas dos componentes

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#128]

**Comment by arthurcordeiro** [comment]
Cria resizeObserver para o lexml-emenda e ajusta altura ao redimensionar

https://github.com/lexml/lexml-eta/commit/ea8f8343e9f442b552c46d8ff4f2f514e39379aa

**Comment by arthurcordeiro** [comment]
Verifica se já existe um resizeObserver antes de criar outro:
https://github.com/lexml/lexml-eta/commit/2674835452897957f77b6668bd14fe5971253163
