### ISSUE TITLE
Implementar componente de opções de impressão.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#134]
Este componente deve ser apresentado em uma nova aba "Opções de impressão" antes da aba de avisos.

Devem ser apresentado um formulário com:

```
X   Imprimir brasão. <checkbox>

Texto do cabeçalho:
________________________________________________ <input de texto de preenchimento não obrigatório>

X   Reduzir espaço entre linhas. <checkbox>
```

Componente responsável por preencher o atributo Emenda.opcoesImpressao

```
export class OpcoesImpressao {
  imprimirBrasao = true;
  textoCabecalho = '';
  reduzirEspacoEntreLinhas = false;
}
```

Lembrar de tratar o salvar, abrir e notificar onchange.

**Comment by arthurcordeiro** [comment]
Cria componente de opções de impressão e renomeia aba de data e autoria:
https://github.com/lexml/editor-emendas/commit/b98f9072c42c8c6646f4d2eeeea6462d63da47f3

Falta salvar no json, @DennysMarinho
