### ISSUE TITLE
Só permitir finalizar bloco de alteração no último dispositivo de um grupo de alterações

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#153]
Finalizar um bloco de alteração no meio de várias alterações resulta em uma situação sem sentido para uma emenda, separando as alterações de uma mesma norma em dois artigos diferentes. A situação também é inconsistente em termos de edição do texto porque cria um novo artigo com conteúdo que não é novo.

A opção de finalizar bloco de alteração deve ser proposta apenas no último dispositivo alterado, considerando todos os blocos irmãos.

ANTES (MPV 885/2019)

![image](https://user-images.githubusercontent.com/5323676/170141199-5e10d682-17ee-470c-82df-a4607c612ea2.png)

DEPOIS

![image](https://user-images.githubusercontent.com/5323676/170141490-c787fc3b-086f-4c13-9eef-bafbf6b6b19c.png)

**Comment by jholanda** [comment]
Foi desabilitada essa funcionalidade pois agora é possível criar um artigo antes e depois

**Comment by fragomeni** [comment]
@jholanda, gostei da solução. A ação de finalizar bloco de alteração é até meio confusa para o usuário.
