### ISSUE TITLE
Não validar pontuação final de dispositivo seguido de omissis.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#166]
Verificado nos testes pelo Rogério

![image](https://user-images.githubusercontent.com/5323676/170717433-43d9253d-6b75-4c9b-a08e-e9a1856dfe76.png)

Considerar validações de dispositivos que deveriam terminar com dois pontos, ponto, ponto e vírgula e ponto e vírgula seguido de 'e' ou 'ou'.

**Comment by jholanda** [comment]
Não está muito claro ainda o tratamento de casos envolvendo omissis, pois se trata de um caso muito amplo e, portanto, ainda não estão claramente definidas as operações possíveis quando aparecem omissis "genéricos"
