### ISSUE TITLE
Substituir elix por shoelace no diálogo de informar norma alterada

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#168]
Em InformarNormaDialog.ts.

Para testar:
- Adicionar artigo
- Inserir bloco de alteração
- Informar norma alterada (no menu do artigo)

**Comment by arthurcordeiro** [comment]
index.ts:
- importa componentes do shoelace dialog, menu-item, select, input e button;

informarNormaDialog.ts:
- Substituído dialog, input, select, alert e button por componentes do shoelace;
- Previne fechar dialog quando clica no overlay;
- Trata formato da data do input shoelace para o esperado por validaUrn();

src/icons:
- adiciona ícone check-lg.svg;
- adiciona ícone chevron-right.svg;

https://github.com/lexml/lexml-eta/commit/34f1fd94b04c9d03eec5947b23ffd688b556a2d0
