### ISSUE TITLE
Substituir elix por shoelace no diálogo de numerar e criar rótulo para o dispositivo

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#169]
editor.component.tx renumerarElemento

**Comment by arthurcordeiro** [comment]
index.ts:
- importa sl-radio-group e sl-radio-button do shoelace.

editor.component.ts:
- substitui dialog, input, radio button e buttons pelos do shoelace;
- esconde radio group quando inciso.

![Image](https://user-images.githubusercontent.com/1903603/171940925-7a758b9d-3f72-4c5c-b96c-1a1d1e899ff0.png)
![Image](https://user-images.githubusercontent.com/1903603/171940926-b0f5710c-770c-4512-86ae-5bcd6c38c77d.png)

https://github.com/lexml/lexml-eta/commit/7cabe35c051c834171e5db14b21d894b1d484976
