### ISSUE TITLE
Substituir elix por shoelace no popup de confirmação

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#171]
editor.component.ts 
confirmar()

Apresentado na confirmação de exclusão de dispositivo.

**Comment by arthurcordeiro** [comment]
removerElemento():
- ajusta event.detail.closeResult para retorno do botão cllcado

confirmar():
- cria dialog, mensagem, buttons e listerners dos componentes sholace
- Evita fechar ao clicar no overlay;
- Define closeResult de acordo com o botão clicado.

![Image](https://user-images.githubusercontent.com/1903603/172478518-42e060a6-5073-4f04-827e-16a75c9c8f8f.png)

https://github.com/lexml/lexml-eta/commit/d42a612a64400c83679d0397de8e309b3c8da2f4
