### ISSUE TITLE
Ajustes de layout no componente de autoria

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#173]
1. Remover barra de rolagem da lista de parlamentares enquanto não for necessária.
2. Usar cursor de ponteiro na seleção do parlamentar.

![image](https://user-images.githubusercontent.com/5323676/170785842-0a16b360-6fd3-4799-be40-0193cf207b6e.png)

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/lexml-eta/commit/e965c816563fda8c5ba7206200c9dfc7d77d24c8
