### ISSUE TITLE
Criar indicação visual de que os rótulos de dispositivos adicionados em bloco de alteração são clicáveis.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#207]
Nada indica visualmente que o rótulo do inciso adicionado é clicável.

![image](https://user-images.githubusercontent.com/5323676/172270211-611a487e-ed76-4d35-a11c-d8badb1bf888.png)

**Comment by arthurcordeiro** [comment]
Criada border-bottom dashed

![Image](https://user-images.githubusercontent.com/1903603/172680366-fd6817e9-b956-488f-b7d7-0003c92e6fe4.png)

https://github.com/lexml/lexml-eta/commit/996c11b5124cfb644d41b1a63bdb88ab7c5636ff
