### ISSUE TITLE
Destacar mensagem de validação na tela de numeração de dispositivo.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#210]
![image](https://user-images.githubusercontent.com/5323676/172270612-4f462009-2484-41c6-9f00-b1f5e99b3e22.png)

A padronização da forma de validação nos popups será feita mais tarde.

**Comment by arthurcordeiro** [comment]
Criado alerta no shoelace das 3 mensagens de erro possíveis.

![Image](https://user-images.githubusercontent.com/1903603/172488324-95806fca-36a6-4b75-bc18-4fbd53efdcfc.png)
![Image](https://user-images.githubusercontent.com/1903603/172488325-f511c4e0-9a45-44d8-8ae3-cd1fe830e7a9.png)
![Image](https://user-images.githubusercontent.com/1903603/172488323-4392022b-3566-4801-b73c-e95b75b73205.png)

https://github.com/lexml/lexml-eta/commit/bf016bf420f8032faf8690327263199cf0ba18bb
