### ISSUE TITLE
Melhorar layout de mensagens de erro com opção de correção automática

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#218]
Em vez da mensagem inteira ser clicável, poderia haver um botão com o texto genérico de "Corrigir" ou um link com uma mensagem com a correção específica (ex: "Adicionar omissis" ou "Numerar dispositivo"), ou a solução que você achar melhor.

Exemplo 1:

![image](https://user-images.githubusercontent.com/5323676/173146667-dfa72885-b4f5-48c2-9ae3-0b624db5ef1d.png)

Exemplo 2:

![image](https://user-images.githubusercontent.com/5323676/173147137-20d26e1f-fec5-4e10-b2cf-5620cfea59a0.png)

**Comment by arthurcordeiro** [comment]
Criado um link 'Corrigir agora'

![Image](https://user-images.githubusercontent.com/1903603/173470894-3775b7d3-6816-4be6-beca-ff7be30110e3.png)

https://github.com/lexml/lexml-eta/commit/dab660bab42cd884f6eb8aa1a1364f2b0985477e
