### ISSUE TITLE
Tornar rótulos de dispositivos pesquisáveis na busca de palavras na página usando Ctrl+F

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#226]
Adicionar também a tecla Ctrl+F (Buscar ou Localizar texto) no help de teclas de atalho.

**Comment by arthurcordeiro** [comment]
<img width="529" alt="Captura de Tela 2022-06-14 às 09 57 30" src="https://user-images.githubusercontent.com/1903603/173582638-489f0017-5f66-4fcc-9a23-b80020ef2f4d.png">

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/lexml-eta/commit/2ad210e5b273e046ec769f5f05bce06727f50de2

https://github.com/lexml/lexml-eta/commit/8a9c0f81582ae63977814189e87c445ca8cc9cf1

https://github.com/lexml/lexml-eta/commit/35e6d8024cb1251e47443f0b6057dcfe0731972f
