### ISSUE TITLE
Aplicar classe CSS de existente ou inexistente na norma alterada

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#233]
Para dispositivos adicionados, caso o atributo existeNaNormaAlterada tenha sido informado, deverá ser aplicada uma classe CSS correspondente para permitir alguma diferenciação visual.

**Comment by arthurcordeiro** [comment]
![Image](https://user-images.githubusercontent.com/1903603/173632431-594f7c35-51eb-4fe4-b774-65b00a6c1483.png)

https://github.com/lexml/lexml-eta/commit/8a9c0f81582ae63977814189e87c445ca8cc9cf1

https://github.com/lexml/lexml-eta/commit/8a9c0f81582ae63977814189e87c445ca8cc9cf1
