### ISSUE TITLE
Traduzir botões de formatação para português

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#239]
No texto e na justificativa.

![image](https://user-images.githubusercontent.com/5323676/173194789-9ee879d9-e0b0-46eb-8b8d-decda130c1df.png)

**Comment by arthurcordeiro** [comment]
- Cria arquivos negrito.svg e sublinhado.svg;
- Substitui ícones bold e underline do quill

![Image](https://user-images.githubusercontent.com/1903603/175351359-e76aacc6-6094-421c-911b-3805d88e728d.png)

![Image](https://user-images.githubusercontent.com/1903603/175351437-b8b86338-c4de-47fc-8731-12639767a6e6.png)

https://github.com/lexml/lexml-eta/commit/1fad12478afb6168a82da60c00b2503a531490ff

**Comment by arthurcordeiro** [comment]
Fazer N mais gordinho

**Comment by arthurcordeiro** [comment]
![Image](https://user-images.githubusercontent.com/1903603/175987866-db5fb94b-00cf-48a2-9968-27bf77fe73a7.png)

https://github.com/lexml/lexml-eta/commit/be5d7391496e03b4969551954029621eebf64dbd
