### ISSUE TITLE
Remover popup de confirmação de exclusão ao teclar Ctrl+D e já excluir

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#246]
Reproduzir o mesmo comportamento do menu.

Inclusive não está funcionando a exclusão como popup.

IMPORTANTE: O popup está sendo apresentado no caso de dispositivos originais e modificados. Nesses casos, deve ser apresentada uma mensagem de "Operação não permitida" informando que "Só é possível remover dispositivos adicionados."

----

[Vitor]
pessoal, uma primeira questão com relação à usabilidade que eu achei estranha. Quando você tenta remover um dispositivo apertando "backspace", ele é deletado imediatamente. Já quando você tenta remover um dispositivo usando o comando disponível na abinha lateral esquerda (os 3 pontinhos), ele abre uma caixa de diálogo perguntando se você deseja realmente remover o dispositivo. Não sei se é intencional, mas acho estranho desta forma. Ou abre sempre a caixa pedindo confirmação da remoção, ou não abre nunca. Eu pessoalmente acho desnecessária essa caixa de diálogo, ficando mais fluido o uso da ferramenta sem essas interrupções.

isso vale para dispositivos sem texto (vazios).

[Frago]
Boa observação. Não foi intencional. Realmente os dois comportamentos não estão consistentes. Semana passada discutimos internamente se havia mesmo a necessidade da confirmação, dado que é possível sempre desfazer a operação em caso de engano. Antes de corrigir, gostaria de saber se os outros colegas acham importante fazermos essa confirmação.
___________________________________________
Conforme alinhado com o Fragomeni, 28/09/2023:
Grupo: 
Prioridade: Alta
Esforço: P

**Comment by robsonbarrosdf** [comment]
Resolvido nas  branchs release/1.1.0 e develop.
