### ISSUE TITLE
Adicionar agrupador de artigo de dispositivo da MPV

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#260]
Nome da ação: 
“Adicionar agrupador de artigo” quando posicionado em agrupador de artigo
“Adicionar agrupador de artigo antes” quando posicionado em artigo.

**Em um primeiro momento, restringir a ação a agrupadores de artigo fora de blocos de alteração.**

No menu de artigos e de agrupadores de artigo, apresentar a opção de “Adicionar agrupador de artigo” ou "“Adicionar agrupador de artigo antes”, abre um popup de seleção do tipo do agrupador.

O tipo de agrupador pode ser Parte, Livro, Título, Capítulo, Seção ou Subseção.

Quando comandado a partir de um agrupador, o valor default deve ser o mesmo tipo do agrupador selecionado.

Quando comandado a partir de um artigo, o valor default deve ser o mesmo tipo do agrupador em que o artigo está posicionado ou "Capítulo" caso o artigo não esteja em um agrupador.

Quando posicionado em artigo, o agrupador deve ser adicionado antes do artigo.

Quando posicionado em um agrupador de artigo o novo agrupador deve ser posicionado antes do atual no caso de hierarquicamente superior e após o atual nos demais casos.

A alteração na hierarquia de dispositivos originais não altera a sua situação como dispositivo de emenda (não viram dispositivos modificados).

Criar tecla de atalho Ctrl+Alt+G para acesso a esta funcionalidade.

**Para posicionamento do novo agrupador deve ser verificado se antes dele existe algum agrupador superior na hierarquia:**
- Se houver, o novo agrupador será filho do último agrupador superior na hierarquia que o precede. **(1)**
- Caso contrário, o novo agrupador será posicionado na articulação raiz. **(2)**

**Exemplo (1)**
```
Artigo
Capítulo
  Artigo
  Seção
    Artigo
    Artigo << adicionar Seção
```
resultado
```
Artigo
Capítulo
  Artigo
  Seção
    Artigo
  Seção << nova Seção
    Artigo
```

**Exemplo (2)**
```
Artigo
Capítulo
  Artigo
  Artigo << adicionar Título
```
resultado
```
Artigo
Capítulo
  Artigo
Título << novo Título
  Artigo
```

Obs: Possíveis inconsistências como acima (capítulo sem título em uma articulação com título) serão tratadas posteriormente como mensagens de erro ou alertas.

**Para identificação dos dispositivos a serem agrupados (filhos do novo agrupador), deve ser verificada a existência de agrupador posterior a ele que seja do mesmo tipo ou superior na hierarquia.**
- Se houver, devem ser agrupados todos os dispositivos seguintes até o anterior ao agrupador encontrado, respeitando a hierarquia existente entre esses dispositivos. **(3)**
- Caso contrário, serão agrupados todos os dispositivos posteriores. **(4)**

**Exemplo (3)**
```
Artigo
Capítulo
  Artigo
  Artigo << adicionar Capítulo
  Seção
    Artigo
Capítulo
  Artigo
```
resultado
```
Artigo
Capítulo
  Artigo
Capítulo << novo Capítulo
  Artigo
  Seção
    Artigo
Capítulo
  Artigo
```

**Exemplo (4)**
```
Artigo
Capítulo
  Artigo
  Artigo << adicionar Capítulo
  Seção
    Artigo
```
resultado
```
Artigo
Capítulo
  Artigo
Capítulo << novo Capítulo
  Artigo
  Seção
    Artigo
```

**Comment by robsonbarrosdf** [comment]
commit dd76ad4
