### ISSUE TITLE
Numerar e criar rótulo de agrupadores de artigo

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#268]
Tratar também os agrupadores de artigo na funcionalidade de numerar e criar rótulo. 

Os agrupadores de artigo utilizam números romanos.

O tratamento das demais opções de rótulos de parte (PARTE GERAL, PARTE ESPECIAL e uso e números ordinais) seria feito em um segundo momento.

**Comment by robsonbarrosdf** [comment]
terminado no commit dd76ad4
