### ISSUE TITLE
Adicionar agrupador de artigo de dispositivo de norma alterada

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#270]
Esta funcionalidade apresenta algumas diferenças de comportamento em função do tipo do dispositivo de referência (artigo ou agrupador de artigo) e se o dispositivo de referência é ou não cabeça ou pé de alteração.

O dispositivo de referência é o dispositivo a partir do qual a funcionalidade foi ativada.

Dispositivo cabeça de alteração é o que apresenta a abertura de aspas e o pé de alteração o que apresenta o fechamento de aspas e a nota de altertação.

### Quando o dispositivo de referência for um artigo

A ação “Adicionar agrupador de artigo antes” abre o popup de seleção do tipo do agrupador. 

O valor default deve ser o mesmo tipo do agrupador em que o artigo está posicionado ou "Capítulo" caso o artigo não esteja em um agrupador.

O novo agrupador é inserido antes do artigo de referência.

#### Se o artigo for cabeça de alteração

O novo agrupador ficará em grupo de aspas próprio e não terá filhos.

**Exemplo**
```
"Art..." << adicionar Capítulo
```
resultado
```
"Capítulo"
"Art..."
```

#### Se o artigo NÃO for cabeça de alteração

O novo agrupador ficará no mesmo grupo de aspas do artigo e será posicionado de acordo com as mesmas regras do tíquete #260, porém considerando apenas a hierarquia dentro das aspas.

**Exemplo**
```
"Capítulo
   Art ..." << adicionar Seção
```
resultado
```
"Capítulo
   Seção  << nova Seção
      Art ..."
```

### Quando o dispositivo de referência for um agrupador de artigo

A ação “Adicionar agrupador de artigo” abre o popup de seleção do tipo do agrupador.

No popup de seleção do tipo de agrupador devem ser adicionados:
- Indicador de posição: "Antes" ou "Depois".
- Checkbox "Manter no mesmo grupo de aspas".

O valor default do tipo de agrupador deve ser o mesmo tipo do agrupador selecionado.

O default do indicador de posição deve variar em função do tipo de agrupador selecionado. O valor "Antes" deve ser padrão para os tipos hierarquicamente superiores ao tipo do agrupador de referência e, nos demais casos, o valor padrão é "Depois".

O checkbox "Manter no mesmo grupo de aspas" tem valor padrão desmarcado (false) e deve aparecer apenas nos casos de inclusão "Antes" quando o agrupador de referência for cabeça de alteração ou inclusão "Depois" quando o agrupador de referência for pé de alteração.

#### Nos casos em que o novo agrupador deve ser mantido no mesmo grupo de aspas

Estes são os casos em que o checkbox "Manter no mesmo grupo de aspas" NÃO aparece ou aparece e É selecionado.

O novo agrupador ficará no mesmo grupo de aspas do agrupador de referência e será posicionado de acordo com as mesmas regras do tíquete #260, porém considerando apenas a hierarquia dentro das aspas.

**Exemplo**
```
"Capítulo
   Seção << adicionar Subseção depois
      Art..."
```
resultado
```
"Capítulo
   Seção
      Subseção << nova Subseção
          Art..."
```

#### Nos casos em que o novo agrupador NÃO deve ser mantido no mesmo grupo de aspas

Estes são os casos em que o checkbox "Manter no mesmo grupo de aspas" aparece e NÃO É selecionado.

O novo agrupador ficará em grupo de aspas separado e sem filhos.

**Exemplo**
```
"Capítulo
   Seção" << adicionar Seção depois
```
resultado
```
"Capítulo
   Seção"
"Seção" << nova Seção
```

**Comment by robsonbarrosdf** [comment]
terminado no commit dd76ad4
