### ISSUE TITLE
Tratar omissis de artigo em bloco de alteração.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#271]
Exemplo na MPV 1089

![image](https://user-images.githubusercontent.com/5323676/175045688-c4b245b2-9431-41b7-93ed-d341504c14cf.png)

Só tem sentido quando houver agrupador e pelo menos um dispositivo agrupado no bloco de alteração, ou seja, quando as aspas abrirem em um agrupador e fecharem em um outro dispositivo.

Implementar "Omitir artigo" para artigos em bloco de alteração sem abre aspas e sem fecha aspas.

Implementar "Transformar em artigo" para omissis de artigo adicionadas em bloco de alteração.

Testar (e corrigir se for o caso) o alerta de falta de omissis e correção automática entre artigos dentro de um mesmo grupo de aspas (sempre que o artigo anterior não tenha fecha aspas).

Testar (e corrigir se for o caso) exclusão de omissis adicionado.

Testar (e corrigir se for o caso) undo/redo de todas as opções acima.

IMPORTANTE: Testar bastante as funcionalidades de edição de norma alterada e salvar/abrir após a implementação.

___________________________________________
Conforme alinhado com o Fragomeni, 28/09/2023:
Grupo: 
Prioridade: Média
Esforço: M

**Comment by fragomeni** [comment]
Não encontrei as ações abaixo:
- Implementar "Omitir artigo" para artigos em bloco de alteração sem abre aspas e sem fecha aspas.
- Implementar "Transformar em artigo" para omissis de artigo adicionadas em bloco de alteração.

**Comment by robsonbarrosdf** [comment]
Resolvido na branch develop
