### ISSUE TITLE
Colocar " (NR) na mesma linha do rótulo quando o texto do dispositivo estiver vazio.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#276]
![image](https://user-images.githubusercontent.com/5323676/175115419-8b6270e2-fd1a-4fd9-a9c2-d90e7df1ddea.png)

**Comment by arthurcordeiro** [comment]
Define no CSS display: none para o <br> que é adicionado automaticamente.

![Image](https://user-images.githubusercontent.com/1903603/175933269-a1a093fa-0ffc-4732-b669-baa43a84f589.png)

**Comment by arthurcordeiro** [comment]
![Image](https://user-images.githubusercontent.com/1903603/176328045-96e4ae38-8c3c-4e74-8326-52652f0189b7.png)

https://github.com/lexml/lexml-eta/commit/6a534e8243b0cb85f8beac532467a094adbaf980
