### ISSUE TITLE
Adicionar tooltips (alt) nos botões do editor de justificativa.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#285]
A exemplo do editor de articulação.

**Comment by arthurcordeiro** [comment]
![Image](https://user-images.githubusercontent.com/1903603/176341798-e4e0241a-33f3-4f6b-95cd-89412bd34912.png)

https://github.com/lexml/lexml-eta/commit/8876b51953d91e02fb1907462f0022ed9890e644
