### ISSUE TITLE
Apresentar labels de existente e novo dispositivo de norma alterada após o rótulo

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#315]

**Comment by arthurcordeiro** [comment]
Fiz apenas o label existente pois ainda não fizemos o label novo

![Image](https://user-images.githubusercontent.com/1903603/178324705-b4de4f25-b879-4818-9d49-c6a84d5e135f.png)

https://github.com/lexml/lexml-eta/commit/8334196123e3cf2392efef2b2da0805c008a0b93

**Comment by arthurcordeiro** [comment]
Cria classe de label "novo"

![Image](https://user-images.githubusercontent.com/1903603/178373624-c9b1af7e-b7f6-46be-bb58-67a4d0f5f398.png)

https://github.com/lexml/lexml-eta/commit/189a2b9c365bf22ebfb638958f1d11ffdb5aed5d

**Comment by arthurcordeiro** [comment]
fix: Problema ao editar labels novo e existente ao carregar uma emenda salva 

https://github.com/lexml/lexml-eta/commit/8a38712b974e66b724af87920d709d1b78c78977
