### ISSUE TITLE
Padronizar fontes

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#316]
Utilizar letra serifada no texto da norma, justificativa e comando de emenda e sem serifa no restante da interface.

**Comment by arthurcordeiro** [comment]
![Image](https://user-images.githubusercontent.com/1903603/179028448-ecbc7b04-5ef0-4134-844e-8883dee37f4d.png)

https://github.com/lexml/lexml-eta/commit/26167f6977f6d406d99ba37912f697235e4ca6c0
