### ISSUE TITLE
Rever layout do ícone do menu de contexto

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#317]
- Torná-lo mais visível
- Não sobrepor com a borda verde.

**Comment by arthurcordeiro** [comment]
![Image](https://user-images.githubusercontent.com/1903603/178316585-50340f28-57b5-4c5f-a625-09d67476b8bd.png)

https://github.com/lexml/lexml-eta/commit/14d616dc7821a03fb016bb4edb6e93d3c3d4923a
