### ISSUE TITLE
Utilizar atributo "label" no elemento para indicativo de dispositivo existente ou novo na norma alterada.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#320]
Utilizar o mesmo atributo "label" que foi criado para os tipos de omissis

**Comment by arthurcordeiro** [comment]
![Image](https://user-images.githubusercontent.com/1903603/179016071-94f6752f-c778-422b-a171-c53403f0ee10.png)

https://github.com/lexml/lexml-eta/commit/189a2b9c365bf22ebfb638958f1d11ffdb5aed5d
