### ISSUE TITLE
Editor identifica alteração sem alterar o texto

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#323]
Para reproduzir (emenda à MP 85/2019)
- Clicar no inciso V do art 4º dentro da alteração do art 3º.
- Não alterar nada
- Clicar em outro dispositivo
- O editor considera que o dispositivo foi alterado.

![image](https://user-images.githubusercontent.com/5323676/179021188-c91c1c5a-e19a-47f0-9142-0238b92f6804.png)

**Comment by erivanio** [comment]
Corrigir as aspas no parser do jsonix.
