### ISSUE TITLE
Apresentar omissis até o final da linha no comando de emenda (no componente de tela)

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#326]
As omissis, com ou sem rótulo, devem ir até a margem direita do texto justiicado. Não pode haver também quebra de linha nos omissis e entre o rótulo e o omissis.

Qualquer necessidade de alteração na estrutura da citação do comando de emenda deve ser feita apenas no componente de visualização. Não alterar a geração na origem.

![image](https://user-images.githubusercontent.com/5323676/179309398-b5becbf8-9380-438d-8c68-4b13c8365b56.png)

___________________________________________
Conforme alinhado com o Fragomeni, 28/09/2023:
Grupo: Melhoria de Usabilidade
Prioridade: Médio
Esforço: M

**Comment by arthurcordeiro** [comment]
Aguardando ticket de criar pontos com elemento <Omissis/>
