### ISSUE TITLE
Padronizar e melhorar layout das hotkeys apresentadas no menu de contexto

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#327]
Verificar com o João Holanda quais são as ações e hotkeys. Verificar também com ele o caso da seta para cima.

Não acho que esteja ruim como está, mas talvez você prefira melhorar.

![image](https://user-images.githubusercontent.com/5323676/179309786-21a27629-08df-4382-ad8d-6db4baf5f1ac.png)

**Comment by arthurcordeiro** [comment]
![Image](https://user-images.githubusercontent.com/1903603/180836594-4c5708f5-b67e-4660-987f-cc1b9c0ce6a7.png)

https://github.com/lexml/lexml-eta/commit/b7e83a21f1a1a20e5f66d293034e3bc932db6e17
