### ISSUE TITLE
Verificar possibilidade de uso da fonte Gentium Basic para textos da emenda

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#333]
Se possível, utilizar a fonte Gentium Basic (mesma utilizada na impressão do PDF) para os textos serifados.

https://www.1001fonts.com/gentium-basic-font.html

Caso não seja possível, trocar para a Times New Roman.

**Comment by arthurcordeiro** [comment]
![Image](https://user-images.githubusercontent.com/1903603/180865735-d465f0f1-4083-4b4e-a23d-7e1c3b2424e1.png)

![Image](https://user-images.githubusercontent.com/1903603/180865766-cb819350-f054-4cfe-908e-ec4ea57e1d68.png)

https://github.com/lexml/lexml-eta/commit/7f0ab2c40cf265dd9bb94674b07d63fa0cd6ada0#diff-63d82f20f49dbfe28d2836dfc5bc70143501cb938cd69fa465045f5b2da2fc7b

**Comment by arthurcordeiro** [comment]
Feito @fragomeni. 

Sugiro usar a fonte Times mesmo. A Gentium pesa 700 kb e o negrito é muito sutil quase imperceptível.

![Image](https://user-images.githubusercontent.com/1903603/181093714-d9205925-f1b3-4355-84b2-75415a5f574c.png)
