### ISSUE TITLE
Rever textos, layout e ajuda do assistente de alteração de norma

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#334]
O assistente de alteração de norma permite adicionar um artigo alterando uma norma vigente já com o texto do caput e a estrutura de um primeiro dispositivo alterado.

- Verificar melhores textos para menu, labels, mensagens de erro...
- Separar a identificação da norma e dispositivo alterado
- Criar uma ajuda (talvez com tooltip ou componente semelhante) para o preenchimento do dispositivo da norma
  - Exemplo: Pode ser utilizado "parágrafo", "par" ou § para referenciar parágrafo. Ou mostrar exemplos com variações.

Exemplo:

![image](https://user-images.githubusercontent.com/5323676/180506574-0a39da07-6187-407c-95a1-6aaaf107d5b9.png)

![image](https://user-images.githubusercontent.com/5323676/180506811-53be6004-4542-4750-8929-e4ac07767d99.png)

![image](https://user-images.githubusercontent.com/5323676/180506879-b4722423-05bc-43de-9776-0deba2507777.png)

**Comment by arthurcordeiro** [comment]
![Image](https://user-images.githubusercontent.com/1903603/181098021-d2f60ab6-5fce-4c26-8768-923f57084ee8.png)

https://github.com/lexml/lexml-eta/commit/26c939155c5bd284f2fcd2cf90a386fb27ed1b10
