### ISSUE TITLE
Mensagem errada de falta de omissis

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#335]
Situação na MP 1089/2021

![image](https://user-images.githubusercontent.com/5323676/180513859-ef95cf0b-e967-4d50-a9d9-8c65ce4cff75.png)

**Comment by erivanio** [comment]
o bug deve ter sido corrigido em outro commit da branch develop, ao atualizar o minha branch local em 29/07, o erro sumiu
