### ISSUE TITLE
Utilizar tag <Omissis> em vez de pontos na citação do comando de emenda no caso de omissis em novos blocos de alteração.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#340]
Só está ocorrendo no citação de artigos novos da mpv que contém blocos de alteração com omissis.

**Comment by erivanio** [comment]
@fragomeni precisei modificar [essa linha no comando-emenda-util](https://github.com/lexml/lexml-eta/blob/6d39747be67e606aae4d4d83c25796f08dfa60da/src/emenda/comando-emenda-util.ts#L440) para adicionar a tag </Omissis> quando o conteúdo do texto do dispositivo tiver o TEXTO_OMISSIS, seria isso a correção desta issue?

**Comment by fragomeni** [comment]
@erivanio, quase isso. Tem que fazer o replace do TEXTO_OMISSIS por new TagNode('Omissis').toString() no texto e retornar o texto para não perder o fechamento de aspas e nota de alteração quando houver.

**Comment by fragomeni** [comment]
@erivanio, fiz o ajuste.

**Comment by fragomeni** [comment]
Testar mais...
