### ISSUE TITLE
Padronizar utilização de letras maiúsculas nos textos do editor

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#363]
Utilizar sempre a primeira maiúscula e as demais minúsculas, com exceção de nomes próprios caso ocorram.

Rever textos:
- Ações no menu de contexto
- Textos das janelas modais
- Mensagens de erro e alerta
- Demais componentes

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/lexml-eta/commit/c87175a5f06e6ed8c57ac0a8f70346354d530b2d

https://github.com/lexml/editor-emendas/commit/df3b52693a5b5d0d76f24bdc2650600ff103ed39
