### ISSUE TITLE
Protótipo Figma de interface da aplicação v1.0

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#364]
Ver requisitos em #345

**Comment by arthurcordeiro** [comment]
[Editor de Emendas 1.0.pdf](https://github.com/lexml/lexml-eta/files/9292999/Editor.de.Emendas.1.0.pdf

https://www.figma.com/file/oNWIzNIBpKLMmOIcIBLOFU/Editor-de-Emendas-1.0?node-id=37%3A150267
