### ISSUE TITLE
Planejar vídeos de ajuda

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#382]
- Identificar quais vídeos deverão ser produzidos
- Escrever roteiros
- Prever um vídeo de "getting started"

**Comment by eurobertacs** [comment]
Seguem os entregáveis dos itens solicitados

**Identificar quais vídeos deverão ser produzidos:** 
- [Planejamento dos vídeos](https://github.com/lexml/lexml-eta/wiki/Planejamento-dos-v%C3%ADdeos-de-utiliza%C3%A7%C3%A3o-do-Editor-para-os-usu%C3%A1rios)
- [Planejamento do vídeo teaser](https://github.com/lexml/lexml-eta/wiki/Roteiro-do-teaser)

**Escrever roteiros:** 
- [Teaser](https://github.com/lexml/lexml-eta/wiki/Minuta-do-roteiro-teaser)
- [Emenda supressiva](https://github.com/lexml/lexml-eta/wiki/Roteiro-da-Emenda-supressiva)
- [Emenda modificativa](https://github.com/lexml/lexml-eta/wiki/Roteiro-da-Emenda-modificativa)
- [Emenda aditiva](https://github.com/lexml/lexml-eta/wiki/Roteiro-da-Emenda-aditiva)
- [Mais exemplos de adição de dispositivos](https://github.com/lexml/lexml-eta/wiki/Mais+exemplos+de+adi%C3%A7%C3%A3o+de+dispositivos)
- [Como propor a alteração de uma Norma Vigente](https://github.com/lexml/lexml-eta/wiki/Roteiro-de-Emenda-de-Norma-alterada)
- [Diferenciando Suprimir de Remover dispositivo](https://github.com/lexml/lexml-eta/wiki/Roteiro-de-Diferenciando-Suprimir-e-Remover-dispositivo)
- [Transformar dispositivo](https://github.com/lexml/lexml-eta/wiki/Roteiro-de-Transforma%C3%A7%C3%A3o-de-dispositivos)
- [Recursos de formatação e apoio](https://github.com/lexml/lexml-eta/wiki/Roteiro-de-Recursos-de-formata%C3%A7%C3%A3o-e-apoio)

**Vídeos iniciais feitos pelo João**
- [Emenda supressiva](https://www.vidline.com/share/V0X85HLY3G/afb9dbda3a945675be2e26f54c2a20a6)
- [Emenda modficativa](https://www.vidline.com/share/V0XAEH36EB/5274db28c7bae7d5dc585098c406649f)
- [Diferenciando supressão e exclusão (remover)](https://www.vidline.com/share/V072WHV9N3/76074a78d6e546a0cf55d0d5ac7a106a)
- [Alteração da norma](https://www.vidline.com/share/V0766H4NJ4/1e982ada159d10c2603f8ddf322dfd49)
- [Emenda aditiva](https://www.vidline.com/share/V0XG2H8KL2/e483e29d0cb4bbed11fcbbb1934d952d)
