### ISSUE TITLE
Alguns comandos do teclado não funcionaram no Windows Edge

### ISSUE THREAD

**Issue by eurobertacs** [lexml/lexml-eta#399]
Os comandos do teclado abaixo não funcionaram no Windows Edge:

- Ctrl+Shift+A
- Ctrl+A
- Ctrl+Home
- Ctrl+End
- Ctrl+↑
- Ctrl+↓

Seguem anexos dos vídeos:

https://user-images.githubusercontent.com/90227731/185519095-b1aca8a4-0ce3-4272-b643-7f9ebca20bec.mp4
https://user-images.githubusercontent.com/90227731/185519094-75ca0348-01a9-475e-a9b2-42eafa7a34a6.mp4
https://user-images.githubusercontent.com/90227731/185519096-c2ccb884-ae43-4164-a2fb-ef829fbeb763.mp4
https://user-images.githubusercontent.com/90227731/185519097-0652c03c-28ce-49ab-a71d-5cd63595958c.mp4
https://user-images.githubusercontent.com/90227731/185519099-6c0915bb-abce-4565-b3a0-f67e00c37662.mp4
https://user-images.githubusercontent.com/90227731/185519098-fe29ff14-5df1-44b2-9874-34dab042b056.mp4

**Comment by robsonbarrosdf** [comment]
Foi realizado teste com a versão 105.0.1343.53 do Microsoft Edge e as teclas de atalho indicadas no ticket apresentaram o comportamento esperado.
A recomendação é utilizar essa versão do navegador, que pode ser baixada em https://www.microsoft.com/pt-br/edge
