### ISSUE TITLE
Ao adicionar um capítulo, seção, subseção, parte e livro as opções de menu disponíveis exibem o termo Artigo

### ISSUE THREAD

**Issue by eurobertacs** [lexml/lexml-eta#402]
Segue anexo do vídeo ao simular a criação de um capítulo, seção e subseção

https://user-images.githubusercontent.com/90227731/185770802-64b1af99-e6c5-4b0d-8c78-454e443eeefd.mp4

**Comment by fragomeni** [comment]
@eurobertacs, na verdade o erro é outro. O editor deveria adicionar artigo mesmo, antes ou depois do agrupador. A adição de agrupadores ficou para uma nova versão. Vou registrar o bug em outra issue.
