### ISSUE TITLE
Comando de emenda não está sendo atualizado após exclusão do primeiro de artigo em emenda onde couber.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#448]
Para reproduzir:
- Crie uma emenda onde couber;
- Dê um enter criando um novo artigo;
- Exclua o primeiro artigo;
- Verifique que o primeiro artigo permanece no comando de emenda.

![image](https://user-images.githubusercontent.com/5323676/191845194-82d33136-90bb-4373-bdfd-98152b3dcf67.png)

![image](https://user-images.githubusercontent.com/5323676/191845269-baa4c29c-1490-43a8-bc41-e15936b147b2.png)

**Comment by jholanda** [comment]
criar artigo sem informar só gera comando de emenda após informar um texto qualquer em qualquer dispositivo
