### ISSUE TITLE
Permitir informar apenas ano da norma na popup de informar norma alterada

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#461]
Fazer após ajuste de layout em #462 para usar a formatação nova.

Aceitar data ou apenas ano:

![image](https://user-images.githubusercontent.com/5323676/192617459-b02b1b38-3b9c-4afa-a71d-c3823e58bc3c.png)

Nos moldes do assistente

![image](https://user-images.githubusercontent.com/5323676/192617591-2fdc38c5-d5f2-49b3-96e9-d090968e01eb.png)

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/lexml-eta/commit/97d8a5324bceadb61b8b3647ff32cfb0b4b337e4

![Image](https://user-images.githubusercontent.com/1903603/193431442-f5fae2ec-b288-46e0-aff0-72df6a2301cf.png)
