### ISSUE TITLE
Melhorar formatação dos campos relacionados à data da norma no assistente de alteração de norma

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#462]
Colocar os campos de input de data e de ano na mesma linha dos radios.

Ver também #461 (deve ter a mesma apresentação na tela de informar norma alterada)

![image](https://user-images.githubusercontent.com/5323676/192617845-dd6e85f5-6d8f-4a94-974f-1995d37a03d6.png)

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/lexml-eta/commit/c51458fd2879a9e61fd5db03a838e0ead0861d86

![Image](https://user-images.githubusercontent.com/1903603/193117364-5fe11c75-dea7-4a5f-893e-79dcca9c7861.png)
