### ISSUE TITLE
Editor adiciona ".unico" antes da primeira letra digitada em parágrafo único

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#464]
![image](https://user-images.githubusercontent.com/5323676/192633346-42e20f3d-6d1a-485d-be92-630eb04e90b6.png)

**Comment by robsonbarrosdf** [comment]
Tentamos reproduzir o erro, mas não aconteceu novamente.
Caso volte a aparecer, o ticket será reaberto.
