### ISSUE TITLE
Falha no controle do checkbox de impressão do partido e UF.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#466]
Bug reportado pelo usuário:

Selecionei o autor da proposta (Senador Marcos Rogério) e a opção para que não fosse mostrado o seu partido. Deixei o editor aberto e voltei após algum tempo. Quando visualizei a emenda, o nome do autor desapareceu. Quando inseri o nome do parlamentar novamente, o autor surgiu no PDF, mas o partido também foi mostrado, ao contrário do solicitado.

---
Aparentemente relacionado ao #465 

1) Nova emenda
2) Preencher um autor e desmarcar o checkbox de imprimir o partido e uf
3) Voltar no texto e adicionar um artigo
4) Voltar na autoria (o autor foi perdido e o checkbox permanece desmarcado).
5) Informar um autor e visualizar
6) Verifique que o checkbox está desmarcado, mas é apresentado o partido e a uf

**Comment by robsonbarrosdf** [comment]
Resolvido pelo commit https://github.com/lexml/lexml-eta/commit/3930ff2f866a12995431176299b9474c9a3be18e
