### ISSUE TITLE
Dispositivo colado não aparece em verde quando colado sobre dispositivo novo.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#474]
Para reproduzir:

1) Adicione um artigo vazio em uma alteração de norma.

![image](https://user-images.githubusercontent.com/5323676/200639530-bc97eb62-baa4-4fe9-8777-3bbddf0f9b87.png)

2) Cole um artigo, parágrafo ou incisos.

![image](https://user-images.githubusercontent.com/5323676/200639654-991ecd6e-501b-4ba0-90ea-7f683e4af82b.png)

Observe que os dispositivos colados aparecem em preto, apesar de serem identificados como dispositivos adicionados.

**Comment by arthurcordeiro** [comment]
Classe "dispositivo--adicionado" não está sendo adicionada quando cola o texto abaixo em um novo dispositivo:

§ 3º As transferências referidas no caput deste artigo incluirão:

I - as contratadas pelo servidor para cobertura de riscos de invalidez ou morte; e

II - as referidas no § 4º do art. 16 desta Lei.” (NR)

Pedia ao @robsonbarrosdf para ajudar a identificar o problema.

**Comment by arthurcordeiro** [comment]
<img width="839" alt="Captura de Tela 2022-11-17 às 18 01 09" src="https://user-images.githubusercontent.com/1903603/202559363-c98f04ce-aefb-4d82-ade5-ce515204b6c0.png">
