### ISSUE TITLE
Artigo adicionado em início de alteração de norma não é recuperado após abrir o arquivo.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#480]
Ao abrir o arquivo abaixo, o comando de emenda é recuperado mas o artigo que foi adicionado não aparece no texto da MP.

[bug-abrir.json.txt](https://github.com/lexml/lexml-eta/files/10228089/bug-abrir.json.txt) [remover extensão .txt]

**Comment by robsonbarrosdf** [comment]
Resolvido no commit 67e5354
