### ISSUE TITLE
Melhorar layout da popup de adição de agrupadores de artigo

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#483]
![Image](https://user-images.githubusercontent.com/1903603/215181537-bbf4fa0b-d4cd-41f3-a053-e22115df99da.png)

**Comment by arthurcordeiro** [comment]
![Image](https://user-images.githubusercontent.com/1903603/215181698-9d1877a6-63fb-4509-a02c-a1314d04dc1c.png)


https://github.com/lexml/lexml-eta/commit/43d9dc76ff9094eee95d80bcaef0dea1b32b7f7f
