### ISSUE TITLE
esse projeto está ativo?

### ISSUE THREAD

**Issue by ghost** [lexml/lexml-eta#484]
Olá a todos.

esse projeto está ativo?

*gostaria de contribuir com algumas ideias*

**Comment by jholanda** [comment]
Boa noite,

Está bem ativo sim embora estejamos agora mais voltados para um editor de emendas, já disponível no congresso nacional, que utiliza esse componente:
https://github.com/lexml/editor-emendas

E será um prazer ouvir suas ideias!

Abs

João Holanda
