### ISSUE TITLE
Aumentar a letra e espaço entre parágrafos na edição da justificativa

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#496]
Usar mesmo tamanho de letra do texto da proposição.

Separar um pouco os parágrafos para marcar melhor. (proporção semelhante ao que como aparece no pdf)

Solicitado pelo Adriano, Consultor da CD.

**Comment by arthurcordeiro** [comment]
![Image](https://user-images.githubusercontent.com/1903603/217602076-9ec0adb1-515c-435d-8749-7ac51f7acc0a.png)
![Image](https://user-images.githubusercontent.com/1903603/217602077-b305f032-d308-403f-9ec7-e31a3690a88f.png)

https://github.com/lexml/lexml-eta/commit/fb7ba85a8e9a0c925638483023a17754bd1c21c5
