### ISSUE TITLE
Não apresentar alerta de iniciais minúsculas para incisos, alíneas e itens iniciando com R$

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#508]
![image](https://user-images.githubusercontent.com/5323676/217104933-90956844-3230-4830-90f3-124141bbd4ba.png)

**Comment by arthurcordeiro** [comment]
feat: Não apresenta alerta de iniciais minúsculas para incisos, alíneas e itens iniciando com R$ e alerta caso tenha r$ (minúsculo)

https://github.com/lexml/lexml-eta/commit/3ad36e6095235a5635c238fa114f2e86a97888d3

![Image](https://user-images.githubusercontent.com/1903603/221037765-56a3045a-18aa-4560-9e11-7d5be7a22a9f.png)
