### ISSUE TITLE
Corrigir efeitos colaterais após correção do tíquete #505

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#526]
Após remoção das tags de fechar aspas e nota de alteração para dipositivos que não fecham aspas feita no tíquete #505 ocorreram os seguintes problemas:

Não aparece mais a linha para digitação da denominação de novos agrupadores de artigo
![image](https://user-images.githubusercontent.com/5323676/222242290-43bc2399-d402-435f-8f58-727f639c59bc.png)

Seta para cima e para baixo deixa de funcionar em alguns casos específicos para dispositivos adicionados vazios
![image](https://user-images.githubusercontent.com/5323676/222243487-e7ddbd0d-3dbd-438b-b1e8-55290a04fe84.png)

Para reproduzir: Adicione inciso I-1 no art 1º da MP 905, posicione o cursor no final do inciso II e tecle seta para cima.

**Comment by arthurcordeiro** [comment]
Corrigido efeitos colaterais no Chrome e Firefox
![Image](https://user-images.githubusercontent.com/1903603/224075227-06cc742d-4d8a-4e13-9b28-82eb78b2945b.png)

![Image](https://user-images.githubusercontent.com/1903603/224075294-29dd15bd-eefa-464c-bc81-17743820bdac.png)

https://github.com/lexml/lexml-eta/commit/f2078d4ea9f240b229c919ba1034600bdbe48207
https://github.com/lexml/lexml-eta/commit/4f3382fc7edc62251e08851a23d5392a24080fbc
https://github.com/lexml/lexml-eta/commit/87a5605b4b27cf1ab4d59a55e5e5cc916975aacf
