### ISSUE TITLE
Criar leiaute de modal com opções de colar

### ISSUE THREAD

**Issue by arthurcordeiro** [lexml/lexml-eta#529]

**Comment by kailinerocha** [comment]
Entrega 02/03 

Proposta de modal para funcionalidades: 
    - Copiar e colar 
    - Adicionar ou Substituir novos incisos
    - Colar agrupadores de artigos
    - Colar agrupadores de artigos de níveis diferentes

[Proposta modal - copiar e colar dispositivo.pdf](https://github.com/lexml/lexml-eta/files/10912875/Proposta.modal.-.copiar.e.colar.dispositivo.pdf)

@robsonbarrosdf @fragomeni

**Comment by kailinerocha** [comment]
Conforme a reunião que aconteceu no dia 06/03 às 10h30. Estou estudando a nova especificação #502 colar dispositivo da MP para propor uma nova modal de acordo com os novos requisitos.

**Comment by kailinerocha** [comment]
Entrega 08/03

Proposta de modal para cenário colar artigos. Foi o que pude entender da especificação mas podemos debater melhor na daily.



[Modal colar artigos.pdf](https://github.com/lexml/lexml-eta/files/10925585/Modal.colar.artigos.pdf)

@fragomeni @robsonbarrosdf

**Comment by kailinerocha** [comment]
Entrega 15/03

Documento com todas as propostas de acordo com a última especificação feita (14/03).

[Interface Modal - mensagens de retorno.pdf](https://github.com/lexml/lexml-eta/files/10981938/Interface.Modal.-.mensagens.de.retorno.pdf)

@fragomeni @robsonbarrosdf
