### ISSUE TITLE
Projeto das marcas de revisão de manipulação de dispositivos

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#548]
Verificar requisitos em: 
- https://github.com/lexml/editor-emendas/issues/147

Tratar
- Edição
- Undo
- Arquivo (por último após validar a arquitetura)

Tipos de marcas de revisão
- Manipulação de dispositivos
- Edição de texto (justificativa e revisão de dispositivos adicionados e modificados)

----------------------------------------------

Requisitos -----------------
- Ativar e desativar modo de controle de alteração
- Identificar o usuário que propôs as alterações ou poder registrar alterações anônimas
- Identificar a data/hora das alterações.

class Usuario {
    nome: string = "Anônimo", // para apresentação na interface
    id: any // para identificação no sistema host
}

State.emRevisao: boolean // está ou não em revisão
State.usuario: Usuario

class Revisao {
    tipo: enum com descrição padrão ou máscara de descrição; // ação de revisão
    descricao: string; // descrição do que foi alterado (padrão ou com algum detalhe específico)
    usuario: Usuario;
    dataHora: string; // data no formato ISO, sem timezone, até segundo "yyyy-MM-dd'T'HH:mm:ss"
}

Criar interface no componente para informar usuário que está editando
Revisões anônimas são identificadas por um usuário com valores default

Interface:
- Toggle na barra de botões do texto da proposição (label "Controlar alterações")
- Ícone do lado direitor de cada dispositivo com pequeno popup mostrando usuário e data da alteração e botões de aceitar e rejeitar
- O popup pode aparecer com mouse over ou clicando (para o caso de mobile)

Requisitos -----------------
- Indicador visual de que existem marcas de revisão no documento (na interface e no documento).

Interface:
- Mostrar badge na barra de botões do texto da proposição (texto "Existem marcas de revisão")
- Imprimir alerta no PDF de que o documento possui marcas de revisão (barra com fundo amarelo antes do comando de emenda)

Requisitos -----------------
- Ao controlar alterações passamos a registrar todas as alterações feitas no texto da proposição (MP)

Manipulação de dispositivos:
- Tratar revisões separadas dos dispositivos
- Apresentar elementos revisados com fundo amarelo bem claro

State.revisoes = Array<Revisao>

class Revisao {
    tipo: enum com descrição padrão ou máscara de descrição; // ação de revisão
    descricao: string; // descrição do que foi alterado (padrão ou com algum detalhe específico)
    usuario: Usuario;
    dataHora: string; // data no formato ISO, sem timezone, até segundo "yyyy-MM-dd'T'HH:mm:ss"
    elementoAntesRevisao: Elemento
    uuidRevisado: uuid do Elemento/Dispositivo (deve ser corrigido sempre que ocorrer alteração de uuid para um dispositivo)
    uuidPosicaoAntesRevisao: uuid do elemento anterior (usado para remoção na revisão, deve ser corrigido sempre que ocorrer alteração)
}

>> Abandonar supressão (mesmo caso para abandonar modificação)
d.situacao = suprimido
- abandonar modificações
d.situacao = original
State.revisoes [
    {
        tipo: 'ABANDONAR_SUPRESSAO', descricao = 'Supressão abandonada', usuario, dataHora
        elementoAntesRevisao = { situacao = suprimido }
        uuidRevisado: d.uuid
    }
]

>> Adicionar
- adicionar
d.situacao = adicionado
State.revisoes [
    {
        tipo: 'ADICAO_DISPSITIVO', descricao = 'Dispositivo adicionado', usuario, dataHora
        elementoAntesRevisao = undefined
        uuidRevisado: d.uuid
    }
]

>> Remover
d.situacao = adicionado
- remover
State.revisoes [
    {
        tipo: 'REMOVER_DISPOSITIVO', descricao = 'Dispositivo removido', usuario, dataHora
        elementoAntesRevisao = { situacao = adicionado }
        uuidRevisado: undefined
        uuidPosicaoAntesRevisao: uuid do elementoo imediatamente anterior
    }
]
-- Apresentar o elementoAntesRevisao sem dispositivo correspondente na hierarquia
-- As ações podem ser apenas: aceitar ou rejeitar revisão.
-- Reajustar uuidPosicaoAntesRevisao caso este seja removido ou caso seja adicionado outro elemento entre uuidRevisado e o novo

Interface:
- Apresentar o tipo do dispositivo no rótulo do primeiro dispositivo na hierarquia de removidos na revisão
- Apresentar esses dispositivos taxados em verde.

>> Modificar após abandonar abandonar supressão
d.situacao = suprimido
- abandonar modificações
d.situacao = original
State.revisoes [
    {
        tipo: 'ABANDONAR_SUPRESSAO', descricao = 'Supressão abandonada', usuario, dataHora
        elementoAntesRevisao = { situacao = suprimido }
        uuidRevisado: d.uuid
    }
]
- modifica o texto
d.situacao = modificado
State.revisoes [
    {
        tipo: 'MODIFICAR_DISPOSITIVO', descricao = 'Alteração do texto', usuario, dataHora
        elementoAntesRevisao = { situacao = suprimido }
        uuidRevisado: d.uuid
    }
]

---- Undo/Redo

StateEvent.revisoes: Revisao[]

Ao fazer undo/redo restaurar revisões dos StateEvent, substituindo revisões com o mesmo uuidRevisado ou removendo revisões
quando não existir revisão para o uuid do elemento do StateEvent.

O tratamento de StateEvent.revisoes será restrito aos StateType abaixo:

  ElementoModificado = 'ElementoModificado',
  ElementoIncluido = 'ElementoIncluido',
  ElementoRemovido = 'ElementoRemovido',
  ElementoRenumerado = 'ElementoRenumerado',
  ElementoRestaurado = 'ElementoRestaurado',
  ElementoSuprimido = 'ElementoSuprimido',

Requisitos -----------------
- Permitir aceitar ou rejeitar alterações:
    - Pontualmente (uma alteração específica)

Criar StateType para aceite
  RevisaoAceita (elemento atual com registro de revisão para o undo)
  RevisaoRejeitada (elemento atual com registro de revisão para o undo)

No caso de revisão rejeitada devem ser emitidos os eventos necessários à restauração do estado original.

No tratamento de undo/redo restaurar/apagar o registro de revisão associados aos StateType's de revisão.

Interface:
- Botões de aceitar e rejeitar no puopup do ícone lateral

Requisitos -----------------
- Operações desfeitas pelo revisor durante processo de revisão devem ser identificadas como revisões rejeitadas, ou seja,
devem "sumir" com o registro de revisão.

Ex: durante controle de alteração o revisor suprime um dispositivo e restura o mesmo dispositivo. Não deve ficar o registro de
revisão para o dispositivo. Ele volta no caso de undo.

Requisitos -----------------
Cancelar este requisito, pelo menos temporariamente:
- Os registros de alteração continuam aparecendo no texto mesmo após o modo de controle de alterações ter sido desligado.

Restrição
- O controle de revisão só poderá ser desativado se não hover mais marcas de revisão.

Interface:
- Ao tentar desativar o controle de revisão, se houver algum registro de revisão, deve ser apresentada
a mensagem de que "Só é permitido desativar o controle de alteração após tratamento de todas as revisões."

--------------------------------------------

- Ao controlar alterações passamos a registrar todas as alterações feitas no texto da justificativa

- Desfazer e refazer aceitar/rejeitar alterações.

- Permitir aceitar ou rejeitar alterações:
    - Em sequência (navegando próxima/anterior)
    - Todas dentro de um texto selecionado
    - Todas no documento

-------------------------

Protótipo:

branch feat/marcas-revisao

- ativar/desativar controle de alterações
- implementar controles para:
  - supressão
  - restaurar supressão
  - adição
  - remoção
- testar aceitar/rejeitar/undo/redo

**Comment by robsonbarrosdf** [comment]
Restrição implementada na ação de remover dispositivo em modo de revisão para facilitar a implementação de operações de undo e redo: não é permitido remover um dispositivo que possua dispositivos subordinados removidos em modo de revisão.
Exemplo:
![image](https://github.com/lexml/lexml-eta/assets/37158063/c2c657db-29dc-4cdf-9cfb-97fc0b80281f)
