### ISSUE TITLE
Apresentar alerta sobre dispositivos correlatos em cima do comando de emenda

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#556]
Solicitado pelo Zé Roberto via Zap:

...acho que, tendo em vista alguns casos que me deparei durante os testes, é necessário de alguma forma impedir que o parlamentar (deputado ou senador) consiga alterar vários dispositivos diferentes por meio de uma única emenda, pois o aviso não está sendo suficiente para isso.

**Comment by arthurcordeiro** [comment]
"Cada emenda pode referir-se a apenas um dispositivo, salvo se houver correlação entre dispositivos. Verifique se há correlação entre os dispositivos emendados antes de submetê-la."

![Image](https://github.com/lexml/lexml-eta/assets/1903603/e7a0704e-915e-4f9c-9121-1c15700f0c06)

**Comment by arthurcordeiro** [comment]
feat: Diagrama alerta sobre dispositivos correlatos em cima do comando de emenda:
https://github.com/lexml/lexml-eta/commit/83c3d39074481b42df834d0f9500322f98c8dd58

![Image](https://github.com/lexml/lexml-eta/assets/1903603/96dfea5e-687c-46b6-862a-1c43a401432d)
