### ISSUE TITLE
Apresentar disclaimer ao ativar modo de marcar alterações

### ISSUE THREAD

**Issue by ceniravecchi** [lexml/lexml-eta#579]
- Apresentar disclaimer ao ativar modo de marcar alterações
  - Regras
    - Ao ativar o modo de marcar alterações deve aparecer uma mensagem (disclaimer) explicando como o editor irá se comportar e que isso é uma versão inicial da funcionalidade de controle de alterações/marcas de revisão que está sendo implementada.
    - O usuário pode optar por não ver novamente este disclaimer.
      - Esta informação deve ser registrada no navegador.
  - Já propor um texto para ser validado
  - Responsável: Arthur

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/lexml-eta/commit/57c8cccc9f22576bb3ef5d76e66c09cf6b0a906a


![Image](https://github.com/lexml/lexml-eta/assets/1903603/de9a6a4c-c830-4465-9f8f-b1abc9f30ade)

**Comment by eurobertacs** [comment]
Testes manuais executados para demanda. Maiores detalhes, consulte a issue #624
