### ISSUE TITLE
Interface para identificação e remoção das marcas de revisão na justificativa

### ISSUE THREAD

**Issue by ceniravecchi** [lexml/lexml-eta#583]
- Prever apresentação do nome de todos os usuários e data/hora da última alteração por cada um.
  - Prever botão/ícone/?? para remover a marca de alteração
  - Responsável: Arthur

**Comment by fecocao** [comment]
- Backend finalizado.
- Ícone/botão provisório com a rotina funcionando, imagem:


![Image](https://github.com/lexml/lexml-eta/assets/25462574/900e4411-b6d8-4f81-9564-33135ee5f366)

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/lexml-eta/commit/87aceca9e8c37e424842f22ab65c78f4ea9ecbdd

![Image](https://github.com/lexml/lexml-eta/assets/1903603/5c716e1f-232a-4343-8c7b-e1eb9143a914)

**Comment by arthurcordeiro** [comment]
![Image](https://github.com/lexml/lexml-eta/assets/1903603/3fc95292-34b9-4313-9f60-b5cc54a62011)

https://github.com/lexml/lexml-eta/commit/0559fcd0dc76b55c07726d461448cdddd460d754

https://github.com/lexml/lexml-eta/commit/927f4681d6c21af05c220ffee83e51cc347025df

https://github.com/lexml/lexml-eta/commit/aadb6c369a9bacf7ffd0faaeb5db175e6c7c67c3
