### ISSUE TITLE
Marcar alterações na edição da justificativa

### ISSUE THREAD

**Issue by ceniravecchi** [lexml/lexml-eta#584]
- Regras
    - Ao marcar alterações passamos a registrar a identificação dos usuários que alteraram o texto da justificativa.
    - Não será mantida no documento a situação original para uma possível recuperação automática.
    - Não é necessário identificar alterações específicas em textos de forma semelhante ao Word ou Google Docs.
    - Para alterações na justificativa, devem ser registrados todos os usuários que alteraram a justificativa;
    - Identificar o usuário que propôs as alterações ou poder registrar alterações anônimas.
    - Identificar a data/hora da última alteração por cada revisor.
    - O usuário poderá remover as marcas de alteração na justificativa.
  - Responsável: Felipe e Arthur

**Comment by fecocao** [comment]
- Criação de registros de marcas de revisão na Justificativa.
- Indicador visual temporário das marcas de cada.

implementação: 



![Image](https://github.com/lexml/lexml-eta/assets/25462574/4ebad431-d7d7-4658-a599-48b3f91e5712)

**Comment by fecocao** [comment]
Backend finalizado.

**Comment by fragomeni** [comment]
Corrigir: Ícone do círculo laranja não aprece no ambiente de homologação.
