### ISSUE TITLE
Aceitar/rejeitar todas as marcas de revisão

### ISSUE THREAD

**Issue by ceniravecchi** [lexml/lexml-eta#586]
- Regras
    -  O usuário pode aceitar ou rejeitar todas as marcas de alteração de uma vez
  - Responsável: Arthur e Felipe

Obs: Existe um bug conhecido no desfazer/undo da rejeição de marcas de alteração quando existem dispositivos adicionados e/ou excluídos durante a revisão.

**Comment by arthurcordeiro** [comment]
adiciona e remove classe revisoes-justificativa-icon__ativo para diferenciar quando tem tooltip de autor de revisão
https://github.com/lexml/lexml-eta/commit/010bc612fbd5485a79d906042e3533751c3f195e

![Image](https://github.com/lexml/lexml-eta/assets/1903603/4195a00a-4cad-4e79-851f-2c891c775240)

**Comment by fecocao** [comment]
Backend finalizado na aceitação e rejeição de todas marcas de revisões de dispositivos.



![Image](https://github.com/lexml/lexml-eta/assets/25462574/1b463fbb-be4b-4d97-8ffe-64a92812396a)

**Comment by fragomeni** [comment]
Aguardando correções do @robsonbarrosdf

**Comment by ceniravecchi** [comment]
Identificado que não é mais necessário.
Cancelado.
