### ISSUE TITLE
Ativar automaticamente o modo de marcar alterações ao abrir uma emenda que contenha marcas de revisão

### ISSUE THREAD

**Issue by ceniravecchi** [lexml/lexml-eta#590]
- Ativar automaticamente o modo de marcar alterações ao abrir uma emenda que contenha marcas de alteração.
  - Responsável: Felipe

**Comment by fecocao** [comment]
Adicionado método responsável por checar o vínculo do estado emRevisao com o switch Marcas de Alterações.
