### ISSUE TITLE
Desabilitar ações (cliques, teclas de atalho) e edição em dispositivos removidos em modo de revisão

### ISSUE THREAD

**Issue by robsonbarrosdf** [lexml/lexml-eta#620]
Os dispositivos que forem removidos em modo de revisão permanecem exibidos na tela, mas devem ter ações desabilitadas. Por exemplo:
- Edição do texto
- Numeração (de rótulo)
- Alteração de status de existência do dispositivo
- Movimentação
- Atualização da nota de alteração

**Obs**: a navegação com o uso do teclado (setas), a seleção do texto para copiar devem manter o funcionamento normal

![image](https://github.com/lexml/lexml-eta/assets/37158063/890fff02-859d-4816-b6c6-0094f258a4b4)

**Comment by eurobertacs** [comment]
Tarefas de testes: #632 e #643.
