### ISSUE TITLE
Parametrizar urls de serviços do lexml-emenda

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#625]
Criar classe LexmlEmendaConfig com urls dos serviços utilizados.

Passar objeto deste tipo como atributo opcional do lexml-emenda 

Procurar serviços por "api/' na pasta /src

Alterar urls existentes para iniciar em "api/"

Utilizar valores existentes como padrão.

Exemplo: urlConsultaParlamentares = 'api/parlamentares'

criar branch feat/issue-625

**Comment by fragomeni** [comment]
Reprovado no teste:

Não funciona o autocomplete de norma

![image](https://github.com/lexml/lexml-eta/assets/5323676/ce5259cb-1575-49b7-b181-5d1f912f17a7)

![image](https://github.com/lexml/lexml-eta/assets/5323676/a9d6f6f3-40fe-4270-acd7-af55fbd53bf6)

**Comment by berkeleyferreira** [comment]
Property  lexmlEmendaConfig foi definida com type: Object para permitir passagem para subcomponentes do lexml-emenda.
Para resolver "Duplicate identifier error" em tempo de execução, a opção skipLibCheck foi configurada para true no tsconfig.json.
