### ISSUE TITLE
Verificar se a versão que utilizamos do Quill suporta o plugin de tabela

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#630]

**Comment by arthurcordeiro** [comment]
https://github.com/soccerloway/quill-better-table

Requisitos
[quilljs](https://github.com/quilljs/quill) v2.0.0-dev.3

Como usa webpack externo para agrupar, deve-se expor Quill ao objeto de janela, como carregar quill.js por tag de script globalmente. Ou talvez seja necessário bifurcar o repositório e criar o que precisa.
