### ISSUE TITLE
Design e implementação da interface de upload e remoção de anexo de emenda de texto livre

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#636]
Deve ser possível anexar ou desanexar um arquivo PDF a ser usado como proposta de adição ou alteração de anexos da proposição.
- Inicialmente apenas um PDF.
- No caso de necessidade de adicionar mais de um anexo, o usuário deverá consolidar os vários anexos em um único PDF.

**Comment by arthurcordeiro** [comment]
Proposta visual do anexo de texto livre
[Editor de Emendas - anexo texto livre.pdf](https://github.com/lexml/editor-emendas/files/11637819/Editor.de.Emendas.-.anexo.texto.livre.pdf)

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/lexml-eta/commit/2173d43fca6ee6af87954e1e47462cf85e46a214

![Image](https://github.com/lexml/lexml-eta/assets/1903603/91785de7-f1ea-48a7-a081-51140efa5353)
![Image](https://github.com/lexml/lexml-eta/assets/1903603/94f36fbd-8859-4041-b0a9-7bab62beb62d)
