### ISSUE TITLE
Chamar mais atenção para os atalhos

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#650]
Discutir com o Frago

**Comment by arthurcordeiro** [comment]
feat: cria badge com pulse na aba de atalhos e remove após o primeiro clique:
https://github.com/lexml/lexml-eta/commit/d3f31681f3c64acc36d724917e58eaac8251339c

![Image](https://github.com/lexml/lexml-eta/assets/1903603/d29b91e1-a5e1-4776-a53d-724cc8d21723)
