### ISSUE TITLE
Falha ao colar dois artigos separados por um agrupador, suprimindo incisos do segundo artigo

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#652]
Reportado pelo Rogério na homologação da Sprint 27

Ao colar ao mesmo tempo um Art 1º e um Art 2º sem incisos, sendo os dois separados no texto original por um agrupador e o Art 2º original possui incisos, os incisos que são suprimidos só aparecem como suprimidos após receberem o foco e também não são restaurados após undo.

Para reproduzir, colar o texto abaixo na MP 1176 substituindo os dispositivos existentes

```
Art. 1º XXXX
Art. 2º XXXX
```

![image](https://github.com/lexml/lexml-eta/assets/5323676/330b8e0b-6285-4360-81f5-1599c4971e74)

Os incisos do Art. 2º só aparecerão como suprimidos após clicar neles.

![image](https://github.com/lexml/lexml-eta/assets/5323676/5f2ff83b-bd80-4ada-8355-b36f94d8c49e)

Comandar undo

![image](https://github.com/lexml/lexml-eta/assets/5323676/7c53fd49-e0b2-4ff4-a5f1-c722f469e15b)

A supressão dos incisos não foi desfeita

**Comment by fecocao** [comment]
Corrigido no commit https://github.com/lexml/lexml-eta/commit/b69b9fdbbf0cd86bf43bc0ba4f9bf7ed49d1b065

**Comment by fecocao** [comment]
Solução ajustada no commit https://github.com/lexml/lexml-eta/commit/3981101f527272ea2524cb7478d400399852a7c4
