### ISSUE TITLE
Desenhar interface para exibição de diferenças de texto

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#657]
Ícone de botão para usuário clicar e abrir modal com diferenças de texto.

Modal com diferenças de texto:
- Sempre mostrar a diferença entre texto atual e texto original da MP no caso de dispositivo modificado;
- Apresentar diferença entre texto revisado e texto do autor no caso de existir revisão com alteração de texto de dispositivo modificado ou adicionado.

Possibilidade:
```
Alterações

Diferenças com o texto original
Nono nono non oo n ono non oono

Diferenças com o texto anterior à revisão
Nonon nono nono nonono n
```

**Comment by arthurcordeiro** [comment]
feat: cria ícone parar o botão diff
https://github.com/lexml/lexml-eta/commit/71c3956010323f4e53ce50f471cca09a684959a2

**Comment by arthurcordeiro** [comment]
![Image](https://github.com/lexml/lexml-eta/assets/1903603/7a5be37b-80ce-46c7-b7cd-077d74c02193)
