### ISSUE TITLE
Apresentação de diffs de textos alterados

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#658]
Implementar botão e modal de apresentação de diffs de textos alterados (ver #657)

Apresentar o botão de diff no caso de dispositivo modificado (revisado ou não) e no caso de dispositivo adicionado com texto alterado em modo de revisão.

**Comment by fecocao** [comment]
Altera título da terceira coluna quando o dispositivo atual está em situação original com revisão de abandono de modificações, modificação para o texto original apagando as alterações anteriormente feitas e etc.

![Image](https://github.com/lexml/lexml-eta/assets/25462574/eb9df0f6-43d7-439e-982b-5e17f314618e)
