### ISSUE TITLE
Menu desaparece quando aciona "Adicionar artigo depois" na ementa, não renumera corretamente e não funciona quando "Marcas de revisão" ativado

### ISSUE THREAD

**Issue by arthurcordeiro** [lexml/lexml-eta#660]
O comando de emenda não é gerado quando isso acontece.

![Image](https://github.com/lexml/lexml-eta/assets/1903603/e37bd07a-de84-40bd-9919-a58fcaca7e38)

**Comment by robsonbarrosdf** [comment]
Corrigido na branch develop
