### ISSUE TITLE
Ajustar altura dos componentes de emenda de texto livre e de justificativa

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#670]
Antes da implementação da emenda de texto livre, a altura do componente da justificativa estava sendo ajustada automaticamente para ocupar toda a altura do componente lexml-emenda.

O mesmo comportamento é esperado para a altura do componente de emenda de texto livre.

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/lexml-eta/commit/ce68d28002ae642d65c3c83f75220138409820b0

![Image](https://github.com/lexml/lexml-eta/assets/1903603/0685aa75-19fb-4b04-9e06-0375335fd153)

![Image](https://github.com/lexml/lexml-eta/assets/1903603/64000368-2625-48d0-8689-9b1343364410)
