### ISSUE TITLE
Colunas da janela modal "Texto alterado" precisam ficar na mesma largura, independente do tamanho do texto

### ISSUE THREAD

**Issue by eurobertacs** [lexml/lexml-eta#673]
![Janela de alterações de texto](https://github.com/lexml/lexml-eta/assets/90227731/58a77684-9e3f-466f-81bb-314e3ff0e23e)

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/lexml-eta/commit/f6b0c1bb021983bc9bfeeffcc095b884e30d7722

![Image](https://github.com/lexml/lexml-eta/assets/1903603/6ebd139e-c770-47c2-985b-fbba6d5fcb61)
