### ISSUE TITLE
Revisão da modal de comparação de texto

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#677]
Alterar o título da modal para "Exibir diferenças do texto atual com"

Apresentar abas "Texto original" e "Texto antes da revisão".

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/lexml-eta/commit/a8c24c3483af5e24b014b2b5864679043a2ee6a8

![Image](https://github.com/lexml/lexml-eta/assets/1903603/f0773813-e81b-4f29-942f-9cdaea296c08)

**Comment by arthurcordeiro** [comment]
@fecocao:

https://github.com/lexml/lexml-eta/commit/049e340c889c7b355e4607a3627e621eb42e0025
