### ISSUE TITLE
O editor está mantendo o estado de marcas de revisão habilitada para novas emendas

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#681]
Para reproduzir:
- Salvar uma emenda com marcas de revisão habilitada
- Inicie a edição de uma nova emenda
- Verifique que as marcas de revisão continuam habilitadas.

Para corrigir, desligar o controle de marcas de revisão sempre que for iniciada uma nova emenda. 

Implementar no branch de release

**Comment by fecocao** [comment]
resolvido no commit https://github.com/lexml/lexml-eta/commit/02d6cdc8ff39f4825fdfab769651229760877c66 da release/0.10.0 e já mergeado com a develop
