### ISSUE TITLE
Diferenças com texto antes da revisão não estão sendo atualizadas após undo/desfazer

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#682]
Reportado durante homologação pelo Rogério. Vídeo abaixo.

https://github.com/lexml/lexml-eta/assets/5323676/5b7f257b-80fb-4ffe-a29d-c0e2e567e656

Fazer no branch de release

**Comment by fecocao** [comment]
corrigido no commit https://github.com/lexml/lexml-eta/commit/6b95382abeb47ad46db9238c317f776278bca213 e já mergeado com a develop.
