### ISSUE TITLE
Editor não identifica alteração de norma ao colar a partir do google docs

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#689]
Para reproduzir:

- Colar o texto abaixo no google docs e tentar copiara a partir do google docs para o editor

Art. 2º A Lei nº 12.087, de 2009, passa a vigorar com as seguintes alterações:
“Art. 7º Teste”

- O editor não identifica a alteração de norma. A citação fica na mesma linha do artigo

![Image](https://github.com/lexml/lexml-eta/assets/5323676/39e71ac7-7682-4afd-87d5-08021634f28b)

**Comment by fecocao** [comment]
Corrigido na release/0.11.0. 
Tratamento de tags html equivalentes a aspas duplas (“ e ”).
