### ISSUE TITLE
Vídeo emenda de texto livre

### ISSUE THREAD

**Issue by arthurcordeiro** [lexml/lexml-eta#700]
___________________________________________
Conforme alinhado com o Fragomeni, 28/09/2023:
Grupo: 
Prioridade: Alta
Esforço: M

**Comment by arthurcordeiro** [comment]
Título: Tutorial: Criando Emendas de Texto Livre com Anexos no Editor de Emendas

Descrição: Aprenda a criar Emendas de Texto Livre no Editor de Emendas do Congresso Nacional e entenda, por meio de um exemplo prático, como adicionar um anexo a uma Medida Provisória.

Transcrição para o Vídeo:

[Introdução]
"Olá! No vídeo de hoje, abordaremos a Emenda de Texto Livre no Editor de Emendas, e lhe mostraremos como adicionar um anexo a uma Medida Provisória. Vamos começar?"

[Explicação]
"A Emenda de Texto Livre é uma ferramenta versátil, ideal para situações onde a emenda padrão não atende. Um dos usos mais comuns é quando precisamos inserir anexos, especialmente em Medidas Provisórias."

[Exemplo Prático]
"Imagine que você precisa emendar uma MP incluindo uma tabela detalhada de gastos ou uma imagem ilustrativa. Aqui vai o passo a passo:

Seleção do Tipo de Emenda: No Editor, escolha 'Emenda de Texto Livre'.
Especificação: Indique o motivo da escolha, neste caso, 'Alteração de anexo de MP'.
Inclusão de Tabelas: Selecione 'Inserir Tabela'. Determine as colunas e linhas e insira seus dados.
Adicionando Imagens: Clique em 'Inserir Imagem'. Selecione o arquivo, ajuste o tamanho e posição.
Finalização: Revise o anexo, garantindo que tudo está claro e compreensível, e conclua sua emenda."
[Conclusão]
"Com a Emenda de Texto Livre, você tem a flexibilidade de enriquecer suas propostas com informações adicionais através de anexos. Use esta funcionalidade com discernimento e torne suas emendas ainda mais completas. Obrigado por assistir, e até o próximo tutorial!"

**Comment by arthurcordeiro** [comment]
# Tutorial: Criando uma Emenda de Texto Livre para alterar anexos de uma MPV

## Introdução
Olá! Neste tutorial, ensinaremos como utilizar a Emenda de Texto Livre no Editor de Emendas com foco em alterações de anexos, usando a MPV 1192 como exemplo.

## Explicação sobre Emenda de Texto Livre
A Emenda de Texto Livre permite ajustes mais detalhados em medidas provisórias, como a alteração de tabelas em anexos. Essa flexibilidade é essencial para atualizações precisas e personalizadas que não são possíveis com o formato padrão de emendas.

## Aplicação na MPV 1192
Vamos ilustrar como fazer uma emenda na MPV 1192, que apresenta um anexo com uma tabela de valores a ser modificada.

### Passos para a Emenda:
1. **Seleção do Tipo de Emenda:** No Editor de Emendas, opte pela 'Emenda de Texto Livre' para começar.
2. **Justificativa da Emenda:** Deixe claro que o objetivo é alterar o anexo para adequar a tabela de valores às necessidades atuais.
3. **Alteração da Tabela:** Acesse o anexo da MPV 1192 e encontre a tabela em questão.
4. **Edição de Conteúdo:** Realize as mudanças necessárias, como editar valores, adicionar ou remover linhas, ou corrigir informações.
5. **Revisão Final:** Confirme se as modificações estão corretas e transparentes para facilitar a compreensão de outros revisores e parlamentares.

## Conclusão
A Emenda de Texto Livre é uma ferramenta valiosa para fazer alterações específicas em textos legislativos. Com este método, você pode assegurar que as modificações em anexos, como tabelas da MPV, sejam feitas de maneira eficaz. Obrigado por sua atenção e convidamos a continuar seguindo nossos tutoriais para mais dicas sobre o uso do Editor de Emendas.

**Comment by robsonbarrosdf** [comment]
**Sugestão 1:**
Trocar 
`Vamos direcionar nossa atenção à MPV 1192. Ela contém um anexo com uma tabela simples que precisa de atualização. Siga estes passos para realizar a alteração corretamente`

por
Vamos direcionar nossa atenção à MPV 1192. Ela contém um anexo com uma tabela simples **e vamos elaborar uma emenda propondo alterações nessa tabela**. Siga estes passos para criar a emenda corretamente

**Sugestão 2:**

Trocar 
`Agora, é essencial justificar sua emenda. No campo apropriado, explique que o anexo da MPV 1192 necessita de atualização na tabela de valores.`

por
Agora, é essencial indicar por qual motivo o tipo emenda de texto livre foi selecionado. Vamos selecionar a opção "Emendamento ou adição de anexos.".

**Comment by arthurcordeiro** [comment]
# Tutorial de Criação de Tabelas no Editor de Emendas - MPV 1192

## Introdução
Bem-vindo ao tutorial onde você aprenderá a criar e editar tabelas diretamente no Editor de Emendas, utilizando como exemplo a MPV 1192.

## Objetivo do Tutorial
O foco é ensinar como inserir novos municípios na tabela do Anexo da MPV 1192, que institui o Auxílio Extraordinário para pescadores artesanais.

## Etapas para a Criação da Tabela
Vamos criar uma tabela fictícia, seguindo o formato do Anexo presente na MPV 1192, e aprender a manusear as ferramentas do editor.

### Passo 1: Acessando o Editor de Emendas
Acesse o Editor de Emendas e escolha a opção 'Emenda de Texto Livre', adequada para inclusão e edição de tabelas.

### Passo 2: Iniciando a Tabela
No campo de edição, inicie a criação da tabela. Use a formatação de tabelas disponível no editor para organizar as informações claramente.

### Passo 3: Preenchendo a Tabela
Digite as informações dos municípios que já constam no anexo original, mantendo a consistência e o formato adequado.

### Passo 4: Adicionando Novos Municípios
Agora, insira municípios fictícios que vamos usar como exemplo. Por exemplo:
- Solares
- Verde Vale
- Aguazul

### Passo 5: Justificativa
Explique a inclusão destes novos municípios com uma justificação genérica, por exemplo:
"A inclusão dos municípios de Solares, Verde Vale e Aguazul visa assegurar que o auxílio chegue a todas as áreas impactadas pela estiagem na região Norte, conforme os objetivos da MPV 1192."

### Passo 6: Revisão e Salvamento
Revise a tabela para corrigir possíveis erros e, em seguida, salve a emenda.

## Conclusão
Através deste processo, você aprendeu a inserir e editar tabelas de maneira eficaz e adequada dentro do contexto da Medida Provisória. Isso conclui nosso tutorial. Obrigado por participar!

**Comment by arthurcordeiro** [comment]
Inserção e edição de tabelas utilizando a emenda de texto livre
https://youtu.be/_i1jDNEBNRw
