### ISSUE TITLE
Video marcas de revisão

### ISSUE THREAD

**Issue by arthurcordeiro** [lexml/lexml-eta#701]
___________________________________________
Conforme alinhado com o Fragomeni, 28/09/2023:
Grupo: 
Prioridade: Média
Esforço: M

**Comment by arthurcordeiro** [comment]
@robsonbarrosdf, segue exemplo de briefing de vídeo tutorial com o Frago
https://drive.google.com/drive/folders/19Cg4su311BcbSenoYCtsCf3ZkbdzHttn

**Comment by arthurcordeiro** [comment]
**Locução para o tutorial de marcas de revisão do Editor de Emendas:**

---

**Introdução (0:00 - 0:30)**
- "Bem-vindo ao tutorial do Editor de Emendas. Aqui, você aprenderá sobre as principais funcionalidades e como utilizar eficientemente esta ferramenta. Vamos começar!"

---

**Marcas de Revisão (0:31 - 2:45)**
- "Começamos com a opção 'Marcas de revisão', localizada na barra de ferramentas. Ao ativar esta opção, qualquer alteração feita no texto será registrada, permitindo que você identifique rapidamente o que foi modificado."
- "Ao ativar 'Marcas de revisão' pela primeira vez, uma janela de alerta aparecerá. Esta janela informa que todas as alterações feitas no texto serão registradas e disponíveis para consulta, garantindo transparência em todo o processo de revisão."
- "Por exemplo, observe o '§ 0º Parágrafo adicionado teste 1'. Esta é uma adição que foi feita e, por isso, está em destaque."
- "Ao lado do texto, você encontrará opções para cada marca de revisão, como 'Diferenças', 'Aceitar', 'Recusar' e 'Autoria'."

---

**Diferenças (2:46 - 4:00)**
- "A opção 'Diferenças' é particularmente útil. Ao selecioná-la, o sistema destaca as alterações feitas no texto, mostrando uma comparação entre a versão anterior e a versão revisada. Assim, você consegue visualizar claramente o que foi adicionado, removido ou modificado."
- "Isso é essencial para assegurar que as mudanças são adequadas e que nada foi alterado acidentalmente."

---

**Opções de Revisão (4:01 - 5:30)**
- "Além de 'Diferenças', temos outras opções de revisão à sua disposição. 'Aceitar' permite que você aprove uma alteração proposta, enquanto 'Recusar' descarta essa mudança."
- "A opção 'Autoria' revela quem fez a alteração, promovendo a colaboração e a responsabilidade durante o processo de edição."
- "No caso de comentários ou justificativas, é possível incluir uma marca de revisão de texto livre, oferecendo contexto adicional ou explicação para a emenda proposta."

---

**Conclusão (5:31 - 6:00)**
- "Com o Editor de Emendas, a revisão de documentos torna-se um processo transparente e colaborativo. Ao utilizar as ferramentas de 'Marcas de revisão', você assegura que todas as alterações sejam devidamente registradas e que a integridade do texto seja mantida."
- "Lembre-se sempre de verificar todas as emendas antes de finalizar, e não hesite em usar a opção 'Diferenças' para ter certeza de todas as modificações feitas."
- "Obrigado por assistir a este tutorial. Esperamos que esta ferramenta facilite seu processo de revisão e edição. Boa sorte e até a próxima!" 

---

**Comment by robsonbarrosdf** [comment]
@arthurcordeiro e @ceniravecchi , ficou muito bom o roteiro.
**Algumas observações:**

- No tópico **Marcas de Revisão**

Acho melhor criar um exemplo de um dispositivo que não seja numerado com zero ("0"). Sugiro pegar um artigo que já possua 2 parágrafos (ou mais) e acrescentar um novo parágrafo após o último já existentes.

O texto atual que menciona "§ 0" está abaixo:
"Por exemplo, observe o '§ 0º Parágrafo adicionado teste 1'. Esta é uma adição que foi feita e, por isso, está em destaque."

- No tópico **Opções de Revisão**

Fiquei na dúvida se o termo "Autoria" poderia ser confundindo com a autoria (parlamentar) da emenda

Em relação ao texto "Se desejar consolidar todas as marcações, você pode utilizar a opção 'Limpar Revisões'. Isso permite que a emenda esteja pronta para desligar o modo de revisão e prosseguir para o encaminhamento.", não temos muita margem para o usuário desejar ou não consolidar as marcações. Atualmente, a única coisa que ele pode fazer é limpar as revisões... ou descartar a emenda.

Por último, talvez valha a pena mencionar o alerta de que emendas contendo marcas de revisão apresentam um alerta, tanto na tela quanto no PDF e que não é recomendável apresentá-las contendo essas marcas. (as revisões precisam ser resolvidas antes)

**Comment by arthurcordeiro** [comment]
# Locução para o tutorial de marcas de revisão do Editor de Emendas

---

## Introdução (0:00 - 0:30)

- "Bem-vindo ao tutorial do Editor de Emendas. Aqui, você aprenderá sobre as principais funcionalidades e como utilizar eficientemente esta ferramenta. Vamos começar!"

---

## Marcas de Revisão (0:31 - 2:45)

- "Começamos com a opção 'Marcas de revisão', localizada na barra de ferramentas. Ao ativar esta opção, qualquer alteração feita no texto será registrada, permitindo que você identifique rapidamente o que foi modificado."
- "Ao ativar 'Marcas de revisão' pela primeira vez, uma janela de alerta aparecerá. Esta janela informa que todas as alterações feitas no texto serão registradas e disponíveis para consulta, garantindo transparência em todo o processo de revisão."
- "Por exemplo, observe o 'Artigo XX, Parágrafo adicionado teste 1'. Esta é uma adição que foi feita e, por isso, está em destaque."
- "Ao lado do texto, você encontrará opções para cada marca de revisão, como 'Diferenças', 'Aceitar', 'Recusar' e um ícone que revela quem fez a alteração."

---

## Diferenças (2:46 - 4:00)

- "A opção 'Diferenças' é particularmente útil. Ao selecioná-la, o sistema destaca as alterações feitas no texto, mostrando uma comparação entre a versão anterior e a versão revisada. Assim, você consegue visualizar claramente o que foi adicionado, removido ou modificado."
- "Isso é essencial para assegurar que as mudanças são adequadas e que nada foi alterado acidentalmente."

---

## Opções de Revisão (4:01 - 6:30)

- "Além de 'Diferenças', temos outras opções de revisão à sua disposição. 'Aceitar' permite que você aprove uma alteração proposta, enquanto 'Recusar' descarta essa mudança."
- "Ao visualizar um ícone indicativo de modificações em 'Justificativa' ou 'Texto Livre', um balão informativo exibe o usuário, data e hora da última edição."
- "Antes de desligar o modo de revisão e encaminhar a emenda, é essencial utilizar a opção 'Limpar Revisões'."
- "Lembre-se: emendas contendo marcas de revisão apresentam um alerta, tanto na tela quanto no PDF. É vital resolver todas as revisões antes de finalizar."

---

## Conclusão (6:31 - 7:00)

- "Com o Editor de Emendas, a revisão de documentos torna-se um processo transparente e colaborativo. Ao utilizar as ferramentas de 'Marcas de revisão', você assegura que todas as alterações sejam devidamente registradas e que a integridade do texto seja mantida."
- "Lembre-se sempre de verificar todas as emendas antes de finalizar, e não hesite em usar a opção 'Diferenças' para ter certeza de todas as modificações feitas."
- "Obrigado por assistir a este tutorial. Esperamos que esta ferramenta facilite seu processo de revisão e edição. Boa sorte e até a próxima!"

---

**Comment by arthurcordeiro** [comment]
Vídeo pronto com legendas para teste/avaliação:
https://youtu.be/GO7wMBLvH0o
