### ISSUE TITLE
Tratar texto grande sem espaços na modal de diff

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#713]

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/lexml-eta/commit/e182c300f039092631aa40940f906c58081a6bbd

Desktop
![Image](https://github.com/lexml/lexml-eta/assets/1903603/cb3fde8e-44df-4327-9d0d-2a5e9fc1e9a5)

Mobile
![Image](https://github.com/lexml/lexml-eta/assets/1903603/80a03067-54bc-4991-8f80-7771d4d3a2fa)
