### ISSUE TITLE
Menu de contexto não está sendo atualizado após abandonar modificações de dispositivo suprimido

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#716]
Para reproduzir:
- Suprima um diapositivo qualquer
- Abandone as modificações
- Clique no menu de contexto e veja que permanece com as opções de dispositivo suprimido (ERRO)
- Clique fora e volte ao dispositivo e veja que o menu foi atualizado como deveria estar no passo anterior

**Comment by robsonbarrosdf** [comment]
Resolvido na branch "release/1.1.0" e feito merge para branch "develop"
