### ISSUE TITLE
Explicar convenção de sufixos de posicionamento de novos dispositivos

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#735]
A explicação deve ser apresentada no momento em que o usuário adicionar um dispositivos da MP que possua um sufixo de encaixe ou rótulo com numeração 0 (zero) ou novo parágrafo após parágrafo único (casos em que aparece o alerta de renumeração).

Deve aparecer um alerta contextual, apenas no primeiro dispositivo (do tipo informado acima) com link para a explicação.

O usuário terá opção de não mostrar novamente.

___________________________________________
Conforme alinhado com o Fragomeni, 28/09/2023:
Grupo: 
Prioridade: Média
Esforço: M

**Comment by arthurcordeiro** [comment]
Sugestão de criar uma mensagem na linha do dispositivo com um link "saiba mais", "entenda melhor"... que abrirá a modal com a explicação e com a opção "Não mostrar novamente"

**Comment by arthurcordeiro** [comment]
feat: cria modal para explicar convenção de sufixos de posicionamento de novos dispositivos
https://github.com/lexml/editor-emendas/commit/9da319c18a424fc60748898d90165fa028b35073

![Image](https://github.com/lexml/lexml-eta/assets/1903603/a8e78624-ed66-41d2-b59b-17abfcb1bc40)

**Comment by arthurcordeiro** [comment]
Preciso da ajuda do @fecocao para apresentar um alerta contextual, apenas no primeiro dispositivo (do tipo informado acima) com link para a modal de explicação
