### ISSUE TITLE
Falha ao abandonar modificações em dispositivos todos em itálico ou negrito

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#741]
Para reproduzir:
- Iniciar emenda ao PL 4687
- Alterar a ementa
- Abandonar modificações
- O dispositivo permanece no estado de modificao (bug)

Provavelmente está relacionado à formatação da emenda em itálico.

O mesmo ocorre para o art. 5º do PLP 197 e art. 1º do PDL 343, que estão todos em negrito.

Pode também estar relacionado à combinação da formatação com o link para a norma.

___________________________________________
Conforme alinhado com o Fragomeni, 28/09/2023:
Grupo: 
Prioridade: Alta
Esforço: P

**Comment by robsonbarrosdf** [comment]
Resolvido nas branchs release/1.1.0 e develop
