### ISSUE TITLE
Aceitar/rejeitar revisão de texto livre (e justificativa)

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#742]
Permitir o usuário aceitar ou rejeitar alterações de texto na tela de visualização de diferenças de revisão da justificativa e do comando de emenda de texto livre.

Ideia: usuário pode clicar sobre diferença e aceitar/rejeitar ou selecionar texto e aceitar/rejeitar todas as alterações no texto selecionado.

___________________________________________
Conforme alinhado com o Fragomeni, 28/09/2023:
Grupo: 
Prioridade: Média
Esforço: G

**Comment by arthurcordeiro** [comment]
feat: cria tooltip com posicionamento contextual para aceite e recusa de revisão
https://github.com/lexml/lexml-eta/commit/8345265a0d69967981092916a66d1738b42938e7

![Image](https://github.com/lexml/lexml-eta/assets/1903603/8ea755d2-5147-4b0f-a4eb-a86958c38587)

**Comment by fecocao** [comment]
Rotinas entregues:
