### ISSUE TITLE
Falha ao colar parágrafos 1º e 2º sobre parágrafo único

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#744]
Para reproduzir, colar o texto abaixo sobre um parágrafo único:

§ 1º Xxxxx
§ 2º Yyyyy

Deveria haver apenas um parágrafo 1º e 2º. O parágrafo único deveria ser substituído.

![Image](https://github.com/lexml/lexml-eta/assets/5323676/731e6596-40e1-4d96-9548-b2faa5a7dcf5)

___________________________________________
Conforme alinhado com o Fragomeni, 28/09/2023:
Grupo: 
Prioridade: Alta
Esforço: M

**Comment by robsonbarrosdf** [comment]
Disponível para teste nas branches release/1.1.0 e develop

**Comment by robsonbarrosdf** [comment]
Tratando colagem sobre alteração ne norma no commit 6202521

**Comment by robsonbarrosdf** [comment]
Correção disponível nas branchs release/1.2.0 e develop
