### ISSUE TITLE
Setar foco automaticamente nas caixas de texto das modais ao abrir

### ISSUE THREAD

**Issue by ceniravecchi** [lexml/lexml-eta#748]
___________________________________________
Conforme alinhado com o Fragomeni, 28/09/2023:
Grupo: Melhoria de usabilidade
Prioridade: Média
Esforço: P

**Comment by arthurcordeiro** [comment]
feat: foca no input radio selecionado após abrir a modal de agrupador
https://github.com/lexml/lexml-eta/commit/10202a3a862d63ff54a0ac62364e5e676876f46c

**Comment by arthurcordeiro** [comment]
feat: foca no input "usuario" após abrir a modal de usuário
https://github.com/lexml/lexml-eta/commit/cd75c8c83a87aa0102feb161e29eb6777265728d

**Comment by arthurcordeiro** [comment]
feat/ux: define o foco no input ao abrir dialog de renumerar elemento
https://github.com/lexml/lexml-eta/commit/7f3be0aabc19d2d9e4d3dcbbce4bb8aedaee8470

feat/ux: ajusta foco ao input da opção default/selecionada ao abrir modal de nota de alteração
https://github.com/lexml/lexml-eta/commit/c804ee384d197222071b376ac50450db7bbf2edd

feat/ux: ajusta foco para o sl-input na modal de largura de imagem
https://github.com/lexml/lexml-eta/commit/11ea13f9fb681c266d600a3c84457bba236ab44c

feat/ux: ajusta foco para o sl-input na modal de alterar largura coluna tabela
https://github.com/lexml/lexml-eta/commit/adbf727fb0ce49712fe90d349b956a13e673b385

feat/ux: ajusta foco ao input de upload ao abrir modal de anexo
https://github.com/lexml/lexml-eta/commit/98559597797390c8c1cc357545da357ca4ac7c2c

**Comment by arthurcordeiro** [comment]
Editor de emendas:

feat/ux: ajusta foco no botão avançar ao abrir modal de orientações
https://github.com/lexml/editor-emendas/commit/9ccdc2d686dab88affaa2124afb59de7705c371b

feat/ux: seleciona e define foco no primeiro radio ao abrir modal de texto livre
https://github.com/lexml/editor-emendas/commit/6cdf202e474c0fb6242faaf58c942361a5511ce8

fix: troca checked=true por click() pra passar pela crítica ao avançar
https://github.com/lexml/editor-emendas/commit/b6615487d041c56b24c2bbd55145a8773833c8df

feat/ux: ajusta foco para o numero-proposicao ao abrir modal e pesquisa ao pressionar enter
https://github.com/lexml/editor-emendas/commit/a1676d38f97ff07f0e8956847fafc612d8915a4c

**Comment by fragomeni** [comment]
Faltou a modal de informar norma alterada.

![Image](https://github.com/lexml/lexml-eta/assets/5323676/010744e9-7054-457b-8e16-ff8578b63096)

**Comment by fragomeni** [comment]
O layout da ementa está ok, mas o foco automático ainda não funcionou.
