### ISSUE TITLE
Ao abrir uma emenda para alterar agrupadores, o conteúdo não é exibido ou será exibido parcialmente

### ISSUE THREAD

**Issue by eurobertacs** [lexml/lexml-eta#753]
Quando foi criada emendas para testar a correção do comando de emenda para agrupadores ao adicionar artigo antes ou depois, o Editor de Emendas funcionou. Porém, ao editar, não foi possível abrir a emenda criada ou a emenda é exibida parcialmente.

Seguem anexos

[EmendasAgrupadores.zip](https://github.com/lexml/lexml-eta/files/12886993/EmendasAgrupadores.zip)

https://github.com/lexml/lexml-eta/assets/90227731/f11fbd69-9adf-43fe-bcf0-bc341fd42310

**Comment by ceniravecchi** [comment]
Não foi possível reproduzir novamente o erro com a mesma emenda.
