### ISSUE TITLE
Limitar o tamanho de anexos a 5MB

### ISSUE THREAD

**Issue by robsonbarrosdf** [lexml/lexml-eta#759]
- Limitar o tamanho de anexos a 5MB
- Apresentar mensagem "O tamanho máximo do arquivo deve ser 5Mb" caso usuário tente adicionar anexo acima de 5MB

**Comment by fecocao** [comment]
Desabilitado botão confirmar caso exista restrições no anexo.

**Comment by fecocao** [comment]
Adicionado tamanhoMaximoAnexo na parametrização lexmlEmendaConfig.

**Comment by ceniravecchi** [comment]
@fecocao , fizemos o teste com o arquivo de tamanho superior a 5Mb numa alteração de Emenda de Texto Livre e a aplicação não criticou (mensagem) que o tamanho é superior ao permitido.
Se tiver dúvida, estou à disposição.

**Comment by fecocao** [comment]
Fiz vários testes a nível de desenvolvimento e não consegui reproduzir o bug mencionado no meu ambiente. O item já foi publicado em homologação pelo @robsonbarrosdf e está funcionando como o previsto, então sugiro mover esse item para pronto para teste/homologação para ser homologado, e criar outro para novas tentativas de reproduzir e corrigir o bug.
