### ISSUE TITLE
Restringir formatação do texto de dispositivos ao colar

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#76]
Ao colar um texto em um dispositivo do tipo artigo ou dispositivo de artigo deve-se aceitar apenas a formatação que pode ser aplicada pelo próprio lexml-eta: negrito, itálico, subscrito, sobrescrito e link para remissão externa. Demais formatações html devem ser desconsideradas.

No caso de agrupadores de artigo, colar sempre apenas texto.

Como exemplo de comportamento comportamento indesejável, experimente copiar o texto de um dispositivo original para dentro de um dispositivo adicionado no modo emenda. O texto colado ficará na cor cinza em vez de verde, como inciso I-A da imagem abaixo:

![image](https://user-images.githubusercontent.com/5323676/164788599-b3923eb0-10ac-4736-bc90-0d429d837c72.png)

**Comment by erivanio** [comment]
![Captura de Tela 2022-05-10 às 08 41 18](https://user-images.githubusercontent.com/5238433/167620426-f0cabbd5-fba3-4833-bf5e-9b54a726f2ba.png)
@fragomeni na justificativa, adiciona link e strike na toolbar e no evento de colar?

**Comment by erivanio** [comment]
![Captura de Tela 2022-05-10 às 09 06 25](https://user-images.githubusercontent.com/5238433/167624495-caaea901-1a09-4298-b449-6e23c617f255.png)
No editor foram habilitadas as tags de link(<a>), negrito(<strong>, <b>), itálico(<i>, <em>), sobrescrito(<sup>) e subscrito(<sub>) #105

**Comment by fragomeni** [comment]
> ![Captura de Tela 2022-05-10 às 08 41 18](https://user-images.githubusercontent.com/5238433/167620426-f0cabbd5-fba3-4833-bf5e-9b54a726f2ba.png) @fragomeni na justificativa, adiciona link e strike na toolbar e no evento de colar ou deixa somente as funções que já estão na toolbar? Atualmente estão no "formats" os mesmos que estão presentes no ToolbarOptions #104

@erivanio, são só os que estão presentes no toolbar.

**Comment by fragomeni** [comment]
> ![Captura de Tela 2022-05-10 às 09 06 25](https://user-images.githubusercontent.com/5238433/167624495-caaea901-1a09-4298-b449-6e23c617f255.png) No editor foram habilitadas as tags de link(A), negrito(STRONG, B), itálico(I, EM), sobrescrito(SUP) e subscrito(SUB) #105

@erivanio, correto. É isso mesmo.

**Comment by fragomeni** [comment]
Ficou ótimo, @erivanio.
