### ISSUE TITLE
Validar pontuação de inciso, alínea ou item quando no final de alteração de norma.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#762]
Caso a alteração de norma termine com uma alínea, inciso ou item, deve ser orientada a utilização de ponto final.

![image](https://github.com/lexml/editor-emendas/assets/5323676/f3d77257-f576-43ea-b927-86583e5ae27b)

___________________________________________
Conforme alinhado com o Fragomeni, 28/09/2023:
Grupo: 
Prioridade: Média
Esforço: P

**Comment by robsonbarrosdf** [comment]
Encontrei um cenário onde a validação da pontuação de inciso não está ok.
Conforme imagem abaixo, o primeiro inciso adicionado apresenta a validação corretamente. Contudo, o segundo inciso adicionado não apresenta a validação.

- Obs. 1: os incisos possuem pais de tipos diferentes)
- Obs. 2: criei um teste unitário para os dois cenários (inciso filho de artigo e inciso filho de parágrafo). O arquivo do teste é **valida-pontuacao-inciso.test.ts**. Os testes relacionados ao cenários 1 estão passando. Dois testes do cenário 2 estão falhando (são os testes que verificam a mensagem de validação).
- Obs. 3: para executar apenas os testes do arquivo **valida-pontuacao-inciso.test.ts** execute o comando abaixo
`npx rimraf out-tsc && npx tsc && npm run copy:quill1table && npx concurrently -k -r "tsc --watch --preserveWatchOutput" "wtr --watch out-tsc\test\redux\valida\valida-pontuacao.test.js"`

![image](https://github.com/lexml/lexml-eta/assets/37158063/6b014f3e-a0df-4b88-a68d-5816a995f922)
