### ISSUE TITLE
Planejar executar teste Limitar o tamanho de anexos a 5MB

### ISSUE THREAD

**Issue by ceniravecchi** [lexml/lexml-eta#766]
#759

**Comment by ceniravecchi** [comment]
[EE_test_plan-2023-10-24_GitHub_766.pdf](https://github.com/lexml/lexml-eta/files/13127472/EE_test_plan-2023-10-24_GitHub_766.pdf)

**Comment by ceniravecchi** [comment]
Demanda retornou para ajuste: o teste com o arquivo de tamanho superior a 5Mb numa alteração de Emenda de Texto Livre e a aplicação não criticou (mensagem) que o tamanho é superior ao permitido.

**Comment by robsonbarrosdf** [comment]
Testes foram refeitos e não foi possível reproduzir cenário de erro.
