### ISSUE TITLE
Foco no primeiro dispositivo ao abrir emenda "onde couber"

### ISSUE THREAD

**Issue by fecocao** [lexml/lexml-eta#774]
Ao abrir uma emenda onde couber com vários dispositivos, o foco e dispositivo selecionado está sendo o último, quando deveria ser o primeiro.

![Image](https://github.com/lexml/lexml-eta/assets/25462574/7a9bd677-b765-4fea-8d75-90e22b5414ac)

**Comment by robsonbarrosdf** [comment]
Resolvido na branch develop do lexml-eta
