### ISSUE TITLE
Emenda de substituição de termo e emenda de texto livre não emitem alerta de falta de justificação

### ISSUE THREAD

**Issue by robsonbarrosdf** [lexml/lexml-eta#775]
Ao criar emenda de substituição de termo ou emenda de texto livre, o editor não emite alerta de que está faltando justificação

**Comment by fecocao** [comment]
Resolvido no commit https://github.com/lexml/lexml-eta/commit/7f6d0fc4bd5214d1d599be681dfd19e8a5f9f091
