### ISSUE TITLE
#lexml-eta Exibir lateral direita com aba "Notas" para emendas de texto livre

### ISSUE THREAD

**Issue by robsonbarrosdf** [lexml/lexml-eta#789]

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/lexml-eta/commit/b16c4efd18a2ad99c9fb97763512f651fc711a89

https://github.com/lexml/lexml-eta/assets/1903603/82c82191-94a0-473a-9c70-d44c93c803ef
