### ISSUE TITLE
Solicitar informar situação na norma vigente para dispositivos adicionados a blocos de alteração.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#79]
Para elaboração do comando de emendas, nos casos de inclusão de dispositivos em blocos de alteração, é necessário que o usuário informe se aquele dispositivo adicionado já existe ou não na norma que está sendo alterada.

Esta informação está registrada no atributo Dispositivo.existeNaNormaAlterada: boolean.

No popup de numeração do dispositivo adicionar a seguinte questão abaixo do input:

**O dispositivo já existe na norma a ser alterada?**
O Sim
O Não

Sem valor default.

**Comment by jholanda** [comment]
Quando um dispositivo da alteração é renumerado, é necessário agora informar a situação dele na norma.

A funcionalidade está ok mas ainda será necessário refatorá-la para utilizar o novo padrão de interface em desenvolvimento.
