### ISSUE TITLE
Bugs Revisão texto rico

### ISSUE THREAD

**Issue by fecocao** [lexml/lexml-eta#793]
- Formato data no tooltip
- Control-Z / Y para refazer revisões aceitas ou rejeitadas precisa ligar o botão de revisão caso esteja desligado
- Criar uma revisão no buildRevisoes (por conta disclaimer não aparecer mais e indicações de revisão no pdf)

**Comment by fecocao** [comment]
- Formato data no tooltip **(resolvido)**
- Control-Z / Y para refazer revisões aceitas ou rejeitadas precisa ligar o botão de revisão caso esteja desligado **(resolvido)**
- Criar uma revisão no buildRevisoes (por conta disclaimer não aparecer mais e indicações de revisão no pdf) **(rever)**

**Comment by fragomeni** [comment]
A data do tooltip não está em um bom formato. Utilizar DD/MM/YYYY HH:MM

![Image](https://github.com/lexml/lexml-eta/assets/5323676/96d974bf-f676-4900-8d28-f12877003e38)

**Comment by fecocao** [comment]
Resolvido formatação da data e hora no commit https://github.com/lexml/lexml-eta/commit/3618695b1e5adc5ba6e04ec1dd8ff0fca057add1



![Image](https://github.com/lexml/lexml-eta/assets/25462574/87ad3c4d-1af9-447e-85a5-70d8f79087ed)



![Image](https://github.com/lexml/lexml-eta/assets/25462574/09e9983f-1e5d-4e88-a06b-6c22e8a90de8)
