### ISSUE TITLE
Modal de explicação de sufixo não está com padrão de letra sem serifa

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#794]

**Comment by arthurcordeiro** [comment]
fix: define padrão de letra sl-font-sans no modal de explicação de sufixo
https://github.com/lexml/lexml-eta/commit/3687b65c6444b24b2c4de9243c4197d718962fd4

![Image](https://github.com/lexml/lexml-eta/assets/1903603/723b070b-07cf-451d-9d2d-18ebd116d5ae)
