### ISSUE TITLE
Parágrafo suprimido ao colar não aparece automaticamente em vermelho taxado

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#795]
Para reproduzir colar o dispositivo abaixo na MPV 1176, alterando o dispositivo existente.

Art. 7º ...............................................
§ 1º ...............................................
I – valor de até R$ 15.000,00 (quinze mil reais) por devedor, considerado o somatório das dívidas financiadas, a ser definido em ato do Ministro de Estado da Fazenda.

Resultado:

![Image](https://github.com/lexml/lexml-eta/assets/5323676/70a9c662-2880-4ba2-8256-9f528d39f4c2)

**ERRO: O parágrafo 2º deveria estar vermelho taxado porque foi suprimido.**

Após clicar no parágrafo 2º a cor do dispositivo é corrigida.

![Image](https://github.com/lexml/lexml-eta/assets/5323676/07994160-f824-4a09-aeeb-d835a458c406)

**Comment by fecocao** [comment]
Em testes da rotina, foi identificado que quando o seguinte texto colado, estão sendo suprimidos dispositivos parágrafos erroneamente.

Texto:

Art. 2º Teste.
§ 1º Teste.
I – valor de até R$ 15.000,00 (quinze mil reais) por devedor, considerado o somatório das dívidas financiadas, a ser definido em ato do Ministro de Estado da Fazenda.

Resultado:

![Image](https://github.com/lexml/lexml-eta/assets/25462574/9542c150-01c9-45f2-9c2b-1436a768e288)

**Comment by fecocao** [comment]
Resolvido no commit https://github.com/lexml/lexml-eta/commit/7dc3e3e00ceea7de079bc584fe5bca94821711bf

**Comment by fragomeni** [comment]
O problema permanece:

![image](https://github.com/lexml/lexml-eta/assets/5323676/f3b0f314-da85-437e-8b2f-06f9eadb8443)

**Comment by fecocao** [comment]
Resolvido a inconsistência no commit https://github.com/lexml/lexml-eta/commit/f0a101ac1b84e869ab82c8db6471b84fca304033
