### ISSUE TITLE
Exigir prefixo http:// ou https:// ao criar/editar link no editor de texto rico

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#798]

**Comment by robsonbarrosdf** [comment]
Resolvido na branch develop

**Comment by fragomeni** [comment]
Está permitindo salvar a URL inválida apesar da mensagem.

Alterar a mensagem para "Digite uma URL válida, iniciando com http:// ou https://"

**Comment by robsonbarrosdf** [comment]
@arthurcordeiro , favor verificar css da janela de inclusão do link
