### ISSUE TITLE
Ao "Abandonar modificações do dispositivo" de um dispositivo com filho adicionado, o filho não está sendo excluído.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#80]
Para reproduzir.

1. Criar emenda à MPV 905/2019.
2. Adicionar inciso I-A ao parágrafo único do artigo 1º.
3. Selecionar "Abandonar modificações do dispositivo" no menu do artigo 1º.

Observe que o iniciso I-A foi transformado em dispositivo original em vez de ter sido excluído, como seria o correto.

**Comment by jholanda** [comment]
Foram definidas nova regras para restaurar dispositivo:

- Se eu modifico o texto do dispositivo original que tem um filho adicionado, modificado ou suprimido,  só o primeiro é restaurado
- Somente no caso de dispositivos suprimidos, os filhos são também restaurados
