### ISSUE TITLE
Criar método para unificar lista de restrições conhecidas.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#800]
Criar método getRestricoesConhecidas(): String[] no componente lexml-emenda com lista de restrições conhecidas do editor.

Utilizar os nomes das opções abaixo:

![Image](https://github.com/lexml/lexml-eta/assets/5323676/cc1e7605-4ace-4788-8478-58a0e9295e70)

**Comment by robsonbarrosdf** [comment]
Resolvido na branch develop
