### ISSUE TITLE
Recuperar alerta de que o documento não deve ser protocolado ao abrir emenda com marcas de revisão apenas na justificação

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#801]
Para reproduzir. Salve uma emenda com marcas de revisão na justificativa e depois abra esta emenda.

Observe que o alerta abaixo deveria aparecer e não aparece.

![Image](https://github.com/lexml/lexml-eta/assets/5323676/477537c4-69ea-44b3-a37b-e0092666ff4d)

**Comment by fecocao** [comment]
resolvido no commit https://github.com/lexml/lexml-eta/commit/5ebf264ed822f9fc62a3a6b373c25bbd33dc1d66

**Comment by fecocao** [comment]
Solução comentada para realizar mais testes em outras situações de alerta

**Comment by fecocao** [comment]
resolvido no commit  https://github.com/lexml/lexml-eta/commit/1f94f0cd1ef863697d7c1faeb3dbc7a87e55846f

**Comment by fragomeni** [comment]
Parou de apresentar o alerta


![Image](https://github.com/lexml/lexml-eta/assets/5323676/ea646056-4f3e-4909-aa76-79cf4ba8c926)

**Comment by fecocao** [comment]
Adicionado timeout para apresentar o alerta e resolveu o problema.

commit https://github.com/lexml/lexml-eta/commit/67e853e6102511dceaad652dfdd74325cebce898

![Image](https://github.com/lexml/lexml-eta/assets/25462574/f56e4367-924e-4668-9945-bcaad5cf4766)
