### ISSUE TITLE
Utilizar "linha pontilhada" em vez de "omissis" nos textos do lexml-eta

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#807]
Trocar para "É necessária uma linha pontilhada antes deste dispositivo"

**Comment by arthurcordeiro** [comment]
feat: utiliza "linha pontilhada" em vez de "omissis" nos textos do lexml-eta 
https://github.com/lexml/lexml-eta/commit/ae504bfba54c6d42c06ed4545682346ef6a96460
