### ISSUE TITLE
Falha na abertura de emenda com omissis de artigo

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#818]
Abrir o arquivo .json abaixo no lexml-eta

[bug abrir com omissis.json](https://github.com/lexml/lexml-eta/files/14102247/bug.abrir.com.omissis.json)

![Image](https://github.com/lexml/lexml-eta/assets/5323676/d91d7f31-1ef3-49c1-a870-37a2f44c7c51)

**Comment by robsonbarrosdf** [comment]
Corrigido nas branchs release/1.5.1 e develop
