### ISSUE TITLE
Não permitir trocar agrupador de artigo de existente para novo se possuir dispositivos subordinados com status de existente

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#819]
![Image](https://github.com/lexml/lexml-eta/assets/5323676/89c2be67-5134-443d-8dab-6f53ba3fdced)

BUG: O editor está permitindo informar que um agrupador de artigo adicionado em uma alteração de norma é novo, mesmo contendo dispositivos existentes.

![Image](https://github.com/lexml/lexml-eta/assets/5323676/c22775c8-7f30-478b-93ec-1d84810f5da7)

Ao tentar trocar o status de um agrupador de artigo de "Existente" para "Novo", verificar se todos os dispositivos diretamente subordinados são novos. Caso algum não seja, falhar com a mensagem abaixo:

Não é permitido mudar a indicação de agrupador "Existente" para "Novo" quando existem dispositivos subordinados com indicação de já existentes na norma.

**Comment by robsonbarrosdf** [comment]
Resolvido nas branchs release/1.5.1 e develop
