### ISSUE TITLE
Oferecer ação "Informar norma alterada" no modo emenda apenas para dispositivos adicionados.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#82]
Não tem sentido uma emenda modifica a referência à norma alterada em um artigo existente.

**Comment by jholanda** [comment]
Quando um dispositivo da alteração é renumerado, é necessário agora informar a situação dele na norma. 

A funcionalidade está ok mas ainda será necessário refatorá-la para utilizar o novo padrão de interface em desenvolvimento.
