### ISSUE TITLE
Mensagem de necessidade de linha pontilhada está aparecendo quando existe linha pontilhada original.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#823]
Abrir o arquivo abaixo no lexml-eta:

[bug linha pontilhada.json](https://github.com/lexml/lexml-eta/files/14113344/bug.linha.pontilhada.json)

![Image](https://github.com/lexml/lexml-eta/assets/5323676/88b5d9ee-1397-4e9b-bbff-361d115cc66b)

**Comment by robsonbarrosdf** [comment]
Resolvido nas branches release/1.5.1 e develop
