### ISSUE TITLE
Split direito aparece ao alterar texto sem borda de arrasto

### ISSUE THREAD

**Issue by ceniravecchi** [lexml/lexml-eta#830]
https://github.com/lexml/editor-emendas/issues/151

![image](https://github.com/lexml/lexml-eta/assets/124091700/1dd87bbd-37f2-4068-825f-e05c1cdd7773)

**Comment by arthurcordeiro** [comment]
![Image](https://github.com/lexml/lexml-eta/assets/1903603/4cbedf9f-0a24-4053-931e-8e25a8f89a54)
