### ISSUE TITLE
Não cria outro artigo ao pressionar o pular linha no teclado mobile

### ISSUE THREAD

**Issue by ceniravecchi** [lexml/lexml-eta#831]
https://github.com/lexml/editor-emendas/issues/151

![image](https://github.com/lexml/lexml-eta/assets/124091700/5e0b7cbe-6be9-4223-a985-0f7aa3116b4e)

**Comment by arthurcordeiro** [comment]
O comportamento mudou. Agora cria outro dispositivo mas ainda acontece o erro de numeração repetida:

https://github.com/lexml/lexml-eta/assets/1903603/95bf97d7-f7b6-49ac-97b3-fcf1be7dfd27

**Comment by arthurcordeiro** [comment]
Pesquisar como debugar no chrome/android

**Comment by ceniravecchi** [comment]
O bug não voltou a ocorrer.
Será excluído.
