### ISSUE TITLE
Modal de diferenças com z-index abaixo do scroll do editor

### ISSUE THREAD

**Issue by ceniravecchi** [lexml/lexml-eta#832]
https://github.com/lexml/editor-emendas/issues/151

![image](https://github.com/lexml/lexml-eta/assets/124091700/428272d5-49bf-441b-9e98-f69d10d2aeb6)

**Comment by arthurcordeiro** [comment]
Resolvido pela remoção do split direito no issue [#830](https://github.com/lexml/lexml-eta/issues/830)

![Image](https://github.com/lexml/lexml-eta/assets/1903603/c274ded1-eaab-424b-aa15-17d219ca7b99)
