### ISSUE TITLE
Menu de tabela abaixo do split direito

### ISSUE THREAD

**Issue by ceniravecchi** [lexml/lexml-eta#833]
https://github.com/lexml/editor-emendas/issues/151

![image](https://github.com/lexml/lexml-eta/assets/124091700/fbf4bbb6-a931-47fd-a725-5ac7d5686ee8)

**Comment by arthurcordeiro** [comment]
Resolvido pela remoção do split direito no issue https://github.com/lexml/lexml-eta/issues/830

![Image](https://github.com/lexml/lexml-eta/assets/1903603/427e56bf-eb6c-4f78-aae9-5bf1208fb95d)
