### ISSUE TITLE
Formulário de substituição de termo

### ISSUE THREAD

**Issue by ceniravecchi** [lexml/lexml-eta#836]
https://github.com/lexml/editor-emendas/issues/151

![image](https://github.com/lexml/lexml-eta/assets/124091700/3d1006f3-f6e3-43ba-a16e-490db84ba9b8)

**Comment by arthurcordeiro** [comment]
https://github.com/lexml/lexml-eta/commit/1a50d829b9bfa68296b604373674c021a43ff765

![Image](https://github.com/user-attachments/assets/c2261094-6af6-4b6e-9c21-d59a799aafc2)
![Image](https://github.com/user-attachments/assets/607fec27-0117-4b08-bffa-5b6dead844cd)
