### ISSUE TITLE
Aceitar sufixos de encaixe com letras ao colar dispositivos da proposição.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#841]
Implementar depois do #840.

Na funcionalidade descrita no tíquete #840, aceitar também sufixos de encaixe com letras (-A, -B...), convertendo para números.

Exemplo: Ao colar um novo art. 1º-A, deve ser adicionado um art. 1º-1 à proposição.

Na implementação, ao identificar esses sufixos com letra, substituir por número e seguir com a implementação já existente.

**Comment by robsonbarrosdf** [comment]
**O código atual já possui o comportamento descrito no ticket.** Isso acontece porque o parser reconhece sufixo com letra.
Assim, ao colar o texto "**Art. 1-A Novo artigo.**", o parser retorna um dispositivo com id "**art1-1**" e esse id é usado na rotina de colagem.
