### ISSUE TITLE
Considerar inserções e deleções sequenciais como uma marca revisão única na revisão de texto rico

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#842]
Quando as alterações do mesmo tipo forem sequenciais, devem ser agregadas em uma única alteração, utilizando a data da alteração mais recente.

No exemplo abaixo, deverá aparecer apenas 2 alterações na contagem em vez de 7.

![Image](https://github.com/lexml/lexml-eta/assets/5323676/52b6c275-ed93-404f-83aa-422e32c46c75)

No caso da inserção de texto, quando digitamos na sequência, está sendo considerada apenas uma alteração, mas se digitamos e voltamos para o início da palavra e digitamos novamente, é contada mais de uma alteração.

No caso da deleção, está sendo considerada uma alteração apenas se selecionarmos um texto e deletarmos todo de uma vez. Deletes ou backspaces sequenciais estão criando várias marcas de alteração.

**Comment by fecocao** [comment]
Corrigido no commit https://github.com/lexml/lexml-eta/commit/2560330ea49d0b965c5cccab5a27d66769ccb98a
