### ISSUE TITLE
Rever troca de rótulo automática de "Parpagrafo único" para "§ 1º" em alteração de norma.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#852]
Ao abrir o arquivo abaixo, o rótulo do parágrafo único acima do parágrafo 2º adicionado deveria ser § 1º.

[paragrafo unico para primeiro em alteracao.json](https://github.com/lexml/lexml-eta/files/14451962/paragrafo.unico.para.primeiro.em.alteracao.json)

Após abrir a emenda, fazer os ajustes necessários na numeração dos rótulos, mantendo os ids.

**Comment by robsonbarrosdf** [comment]
Resolvido na branch develop
