### ISSUE TITLE
Validação de pontuações deveria desconsiderar formatação final do texto

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#873]
Para reproduzir:
- Formatar todo o texto de um artigo com ponto final como negrito

BUG: Verificar aparecimento de mensagem de falta de ponto final dentre outras pontuações.

**Verificar também demais validações de pontuação em tipos diferentes de dispositivos.**

**Comment by arthurcordeiro** [comment]
fix: desconsidera formatação HTML (negrito, itálico, etc...) na validação de pontuações no final do texto https://github.com/lexml/lexml-eta/issues/873

<img width="904" alt="Captura de Tela 2024-04-25 às 15 32 00" src="https://github.com/lexml/lexml-eta/assets/1903603/2f7b5410-2617-4eae-a45a-7dffcc1c6846">
