### ISSUE TITLE
Configurar Cypress no lexml-eta e mover testes de edição de emendas para o lexml-eta

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#877]

**Comment by eurobertacs** [comment]
# Resumo da atividade

* A orientação repassada pelo Fragomeni sobre a instalação do cypress no projeto lexml-eta localmente funcionou com sucesso.
* Foi feita a análise dos seguintes código-fonte do projeto editor-emendas: command.ts, abrir emenda.cy.ts, landing-page.commands.ts e e2e.ts.
* Para a migração para o projeto lexml-eta foram tomadas as seguites ações:
  * Criação do abrir emenda.
  * Alteração do command e e2e com o código migrado e ajustado para o contexto.
  * Geração do json da emenda 3 da MPV 905/2019 que será insumo para automação do abrir emenda.
* Robson e Filipe esclareceram dúvidas sobre o método que carrega a emenda na automação dos testes.
* Apesar da migração feita, ainda contém problemas de compilação e execução, sendo necessário uma continuidade para deixar funcionando por completo e sem erros. Foi feito um commit em função das minhas férias.
* Endereço do commit: https://github.com/lexml/lexml-eta/commit/869f331555a8a1fa9bc9094620cfacd0ca40fab0

**Comment by robsonbarrosdf** [comment]
Configuração concluída e testes já existentes (e pertinentes) foram refeitos no lexml-eta.
