### ISSUE TITLE
Apresentar especificação temática do dispositivo no texto da proposição

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#887]
Em um primeiro momento, não permitir a alteração da especificação temática e informar que para alterar esta especificação deve ser feita uma emenda de texto livre.

Mover junto com o dispositivo imediatamente posterior. Decidir a ideia de utilizar o mesmo elemento do dispositivo na edição.

Considerar esses dispositivos na citação do comando de emenda (verificar como seria).

**Comment by robsonbarrosdf** [comment]
Resolvido na branch **feat/titulo-dispositivo**

Testar com MPV 1170/2023
