### ISSUE TITLE
Apresentar modal informando que o texto da proposição foi dividido em páginas ao iniciar a edição da emenda.

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#899]
Ao iniciar a edição de nova emenda ou abrir uma emenda, caso a proposição esteja paginada, apresentar uma modal informando que a proposição foi divida em páginas e que o usuário pode mudar de página selecionando na barra de ferramentas.

"Esta proposição é muito grande e foi dividida em páginas para facilitar a edição.
A seleção da página para a edição é feita na barra de ferramentas."

Apresentar imagem com trecho da barra de ferramentas ressaltando a combo. (e ou pulsar na combo após fechar a modal)

Botão de fechar ou Ok

**Comment by arthurcordeiro** [comment]
feat: apresenta modal informando que o texto da proposição foi dividido em páginas ao iniciar a edição da emenda.
https://github.com/lexml/lexml-eta/commit/bd11c32684128412b8e2246e4b18d71b21581fff

![Image](https://github.com/user-attachments/assets/d583a535-b20e-4673-90f5-8d6803a5125c)
