### ISSUE TITLE
Apresentar tarja indicando erros de preenchimento no PDF

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#903]
@fecocao faz o front-end e @joaofreitas faz o back-end.

Deve ser apresentada uma tarja no PDF informando que existem pendências de preenchimento da emenda.

Apresentar uma faixa amarela com a frase "O documento contém pendências de preenchimento e não deve ser protocolado até que estas sejam resolvidas:" em negrito, seguido das mensagens de alerta, uma por linha, sem negrito.

Usar mesma formatação do alerta de existência de marcas de revisão.

Utilizar TipoMensagem.CRITICAL para alertas e mensagens que aparecerão no PDF. (depende de #915)

Apresentar no PDF a mensagem do atributo Mensagem.descricaoParaPDF quando preenchido no lugar de Mensagem.descricao.

Salvar mensagens de erro crítico em Emenda.pendenciasPreenchimento removendo a duplicidade de mensagens.

No XML, salvar no elemento:

```
<Emenda>
...
	<PendenciasPreenchimento>
		<PendenciaPreenchimento>Nonon nonon</PendenciaPreenchimento>
		<PendenciaPreenchimento>Nonon nonon</PendenciaPreenchimento>
                ...
	</PendenciasPreenchimento>
```

Considerar como críticos os seguintes alertas/mensagens:

- Alerta.id = alerta-global-comissao-nao-selecionada
- Alerta.id = alerta-global-justificativa
- Alerta.id = alerta-global-emenda-texto-livre
- Mensagem: Não foi informado um texto para ... (descricaoParaPDF: 'Existem dispositivos sem texto informado.')
- Mensagem: Numere o dispositivo (descricaoParaPDF: 'Existem dispositivos de norma alterada sem numeração informada.')

**Comment by fecocao** [comment]
Adicionado testes unitários da rotina de mensagens critical. https://github.com/lexml/lexml-eta/commit/2980a75b7b7d3b46defd98838d73de84e023326f
