### ISSUE TITLE
Setas de navegação não estão considerando edição em múltiplas páginas

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#918]
Abrir o arquivo  [bug-918-setas-entre-paginas.json](https://github.com/user-attachments/files/16548068/bug-918-setas-entre-paginas.json)

As setas de navegação entre alterações do texto deveriam permitir a navegação entre páginas.

![Image](https://github.com/user-attachments/assets/d05e66fe-f025-4e01-830c-d1e7a1562f3e)

**Comment by eurobertacs** [comment]
Ao realizar os testes, incluindo uma alteração em um agrupador para contemplar mais um cenário, as setas conseguem fazer a mudança de página, porém não fica explícito para o usuário que o cursor foi para o dispositivo ou agrupador alterado quando é utilizado a navegação de baixo para cima (seta para cima) para chegar ao topo da página.

Neste caso, o usuário precisa usar a barra de rolagem vertical para visualizar as alterações dos dispositivos ou agrupador no topo da página.

Segue anexo para avaliação: 

[emenda - PLP nº 68, de 2024-issue918.json](https://github.com/user-attachments/files/16641082/emenda.-.PLP.n.68.de.2024-issue918.json)
